/**
 * @file http_aria2.h
 * @brief aria2 implementation of the Abstract Network Interface (ANI).
 *
 * Provides functions to instantiate a transport context backed by aria2 CLI.
 * Handles the mapping between the generic `HttpClient`/`HttpRequest` structures
 * and the specific `aria2c` process.
 *
 * @author Samuel Marks
 */

#ifndef C_CDD_HTTP_ARIA2_H
#define C_CDD_HTTP_ARIA2_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* clang-format off */
#include <c_abstract_http/http_types.h>
/* clang-format on */

/**
 * @brief Initialize the global aria2 environment safely.
 *
 * @return 0 on success, EIO on failure.
 */
extern /**
        * @brief Autogenerated docstring
        */
    int
    http_aria2_global_init(void);

/**
 * @brief Decrement the global initialization reference count.
 */
extern /**
        * @brief Autogenerated docstring
        */
    void
    http_aria2_global_cleanup(void);

/**
 * @brief Initialize a new aria2 context.
 *
 * @param[out] ctx Pointer to a pointer to receive the context.
 * @return 0 on success, ENOMEM or EINVAL on error.
 */
extern /**
        * @brief Autogenerated docstring
        */
    int
    http_aria2_context_init(struct HttpTransportContext **const ctx);

/**
 * @brief Free an aria2 context and its configuration.
 *
 * @param[in] ctx Context to free.
 */
extern /**
        * @brief Autogenerated docstring
        */
    void
    http_aria2_context_free(struct HttpTransportContext *ctx);

/**
 * @brief Apply configuration to the context.
 *
 * @param[in] ctx The context.
 * @param[in] config The configuration to apply.
 * @return 0 on success, EINVAL on error.
 */
extern /**
        * @brief Autogenerated docstring
        */
    int
    http_aria2_config_apply(struct HttpTransportContext *ctx,
                            const struct HttpConfig *config);

/**
 * @brief Perform a single blocking HTTP request via aria2.
 *
 * @param[in] ctx The context.
 * @param[in] req The request.
 * @param[out] res Pointer to receive the response pointer.
 * @return 0 on success, or an error code.
 */
extern /**
        * @brief Autogenerated docstring
        */
    int
    http_aria2_send(struct HttpTransportContext *ctx,
                    const struct HttpRequest *req,
                    struct HttpResponse **const res);

/**
 * @brief Perform multiple HTTP requests concurrently via aria2.
 *
 * @param[in] ctx The context.
 * @param[in] loop The event loop context (unused).
 * @param[in] multi The multi request definition.
 * @param[out] futures Array of futures to populate.
 * @return 0 on success, ENOTSUP if unsupported.
 */
extern /**
        * @brief Autogenerated docstring
        */
    int
    http_aria2_send_multi(struct HttpTransportContext *ctx,
                          struct ModalityEventLoop *loop,
                          const struct HttpMultiRequest *multi,
                          struct HttpFuture **futures);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* C_CDD_HTTP_ARIA2_H */
