/**
 * @file http_libsoup3.h
 * @brief Libsoup3 implementation of the Abstract Network Interface (ANI).
 *
 * Provides functions to instantiate a transport context backed by libsoup3.
 *
 * @author Samuel Marks
 */

#ifndef C_CDD_HTTP_LIBSOUP3_H
#define C_CDD_HTTP_LIBSOUP3_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* clang-format off */
#include <c_abstract_http/http_types.h>

/**
 * @brief Initialize the global libsoup3 environment safely.
 *
 * @return 0 on success, error code on failure.
 */
/* clang-format on */
extern /**
        * @brief Autogenerated docstring
        */
    int
    http_libsoup3_global_init(void);

/**
 * @brief Decrement the global initialization reference count.
 */
extern /**
        * @brief Autogenerated docstring
        */
    void
    http_libsoup3_global_cleanup(void);

/**
 * @brief Create a new libsoup3-backed transport context.
 *
 * @param[out] ctx Double pointer to receive the allocated context.
 * @return 0 on success, ENOMEM on allocation failure, error on init failure.
 */
extern /**
        * @brief Autogenerated docstring
        */
    int
    http_libsoup3_context_init(struct HttpTransportContext **ctx);

/**
 * @brief Free the transport context.
 *
 * @param[in] ctx The context to free. Safe to pass NULL.
 */
extern /**
        * @brief Autogenerated docstring
        */
    void
    http_libsoup3_context_free(struct HttpTransportContext *ctx);

/**
 * @brief Apply configuration settings to the libsoup3 context.
 *
 * @param[in] ctx The transport context.
 * @param[in] config The configuration structure to apply.
 * @return 0 on success, EINVAL if inputs invalid.
 */
extern /**
        * @brief Autogenerated docstring
        */
    int
    http_libsoup3_config_apply(struct HttpTransportContext *ctx,
                               const struct HttpConfig *config);

/**
 * @brief The send implementation for libsoup3.
 * Matches `http_send_fn` signature.
 *
 * @param[in] ctx The transport context.
 * @param[in] req The request.
 * @param[out] res The response.
 * @return 0 on success, error code on failure.
 */
extern /**
        * @brief Autogenerated docstring
        */
    int
    http_libsoup3_send(struct HttpTransportContext *ctx,
                       const struct HttpRequest *req,
                       struct HttpResponse **res);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* C_CDD_HTTP_LIBSOUP3_H */
