/**
 * @file http_wasm.h
 * @brief Emscripten builtin-fetch implementation of the Abstract Network
 * Interface (ANI).
 *
 * Provides functions to instantiate a transport context backed by Emscripten's
 * fetch API for WASM platforms.
 *
 * @author Samuel Marks
 */

#ifndef C_CDD_HTTP_WASM_H
#define C_CDD_HTTP_WASM_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* clang-format off */
#include <c_abstract_http/http_types.h>

/**
 * @brief Initialize the global wasm environment safely.
 *
 * @return 0 on success.
 */
/* clang-format on */
extern /**
        * @brief Autogenerated docstring
        */
    int
    http_wasm_global_init(void);

/**
 * @brief Cleanup the global wasm environment.
 */
extern /**
        * @brief Autogenerated docstring
        */
    void
    http_wasm_global_cleanup(void);

/**
 * @brief Create a new Wasm-backed transport context.
 *
 * @param[out] ctx Double pointer to receive the allocated context.
 * @return 0 on success, ENOMEM on allocation failure.
 */
extern /**
        * @brief Autogenerated docstring
        */
    int
    http_wasm_context_init(struct HttpTransportContext **ctx);

/**
 * @brief Free the transport context.
 *
 * @param[in] ctx The context to free. Safe to pass NULL.
 */
extern /**
        * @brief Autogenerated docstring
        */
    void
    http_wasm_context_free(struct HttpTransportContext *ctx);

/**
 * @brief Apply configuration settings to the context.
 *
 * @param[in] ctx The transport context.
 * @param[in] config The configuration structure to apply.
 * @return 0 on success, EINVAL if inputs invalid.
 */
extern /**
        * @brief Autogenerated docstring
        */
    int
    http_wasm_config_apply(struct HttpTransportContext *ctx,
                           const struct HttpConfig *config);

/**
 * @brief The send implementation for Emscripten fetch.
 *
 * @param[in] ctx The transport context.
 * @param[in] req The request to send.
 * @param[out] res Double pointer to receive the newly allocated response
 * object.
 * @return 0 on success, or a mapped error code on failure.
 */
extern /**
        * @brief Autogenerated docstring
        */
    int
    http_wasm_send(struct HttpTransportContext *ctx,
                   const struct HttpRequest *req, struct HttpResponse **res);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* C_CDD_HTTP_WASM_H */
