/**
 * @file http_libsoup3.c
 * @brief Implementation of the Libsoup3 backend.
 *
 * Handles HTTP requests via libsoup3.
 *
 * @author Samuel Marks
 */

/* clang-format off */
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Defines for C89 string functions if missing */
#if defined(_WIN32) || defined(__WIN32__) || defined(__WINDOWS__)
#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
#define strdup _strdup
#endif
#else
#endif

#include <libsoup/soup.h>

#include <c_abstract_http/http_libsoup3.h>
#include <c_abstract_http/str.h>

/**
 * @brief Opaque context definition.
 */
/* clang-format on */
struct HttpTransportContext {
  SoupSession *session;             /**< The libsoup3 session */
  struct HttpCookieJar *cookie_jar; /**< Weak reference to shared cookie jar */
};

/**
 * @brief Autogenerated docstring
 */
static int g_libsoup3_init_count = 0;

int http_libsoup3_global_init(void) {
  if (g_libsoup3_init_count == 0) {
    /* glib/gio handles its own initialization mostly, but if we needed anything
     * it goes here */
  }
  g_libsoup3_init_count++;
  return 0;
}

/**
 * @brief Autogenerated docstring
 */
void http_libsoup3_global_cleanup(void) {
  if (g_libsoup3_init_count > 0) {
    g_libsoup3_init_count--;
    if (g_libsoup3_init_count == 0) {
      /* Cleanup if needed */
    }
  }
}

/**
 * @brief Autogenerated docstring
 */
int http_libsoup3_context_init(struct HttpTransportContext **const ctx) {
  if (!ctx)
    return EINVAL;

  *ctx = (struct HttpTransportContext *)malloc(
      sizeof(struct HttpTransportContext));
  if (!*ctx)
    return ENOMEM;

  (*ctx)->session = soup_session_new();
  if (!(*ctx)->session) {
    free(*ctx);
    *ctx = NULL;
    return EIO;
  }
  (*ctx)->cookie_jar = NULL;

  return 0;
}

/**
 * @brief Autogenerated docstring
 */
void http_libsoup3_context_free(struct HttpTransportContext *ctx) {
  if (ctx) {
    if (ctx->session) {
      g_object_unref(ctx->session);
    }
    free(ctx);
  }
}

/**
 * @brief Autogenerated docstring
 */
int http_libsoup3_config_apply(struct HttpTransportContext *ctx,
                               const struct HttpConfig *config) {
  if (!ctx || !ctx->session || !config)
    return EINVAL;

  if (config->timeout_ms > 0) {
    g_object_set(ctx->session, "timeout", (guint)(config->timeout_ms / 1000),
                 NULL);
  }

  if (config->user_agent) {
    g_object_set(ctx->session, "user-agent", config->user_agent, NULL);
  }

  if (config->proxy_url) {
    GUri *proxy_uri = g_uri_parse(config->proxy_url, G_URI_FLAGS_NONE, NULL);
    if (proxy_uri) {
      g_object_set(ctx->session, "proxy-uri", proxy_uri, NULL);
      g_uri_unref(proxy_uri);
    }
  } else {
    g_object_set(ctx->session, "proxy-uri", NULL, NULL);
  }

  /* verify_peer / verify_host usually handled via tls-database or signals,
   * skipping complex TLS config for now */

  if (config->cookie_jar) {
    ctx->cookie_jar = config->cookie_jar;
  } else {
    ctx->cookie_jar = NULL;
  }

  return 0;
}

/**
 * @brief Autogenerated docstring
 */
static const char *math_get_method_string(enum HttpMethod method) {
  switch (method) {
  case HTTP_GET:
    return "GET";
  case HTTP_POST:
    return "POST";
  case HTTP_PUT:
    return "PUT";
  case HTTP_DELETE:
    return "DELETE";
  case HTTP_HEAD:
    return "HEAD";
  case HTTP_PATCH:
    return "PATCH";
  case HTTP_QUERY:
    return "QUERY";
  default:
    return "GET";
  }
}

/**
 * @brief Autogenerated docstring
 */
int http_libsoup3_send(struct HttpTransportContext *ctx,
                       const struct HttpRequest *req,
                       struct HttpResponse **const res) {
  SoupMessage *msg = NULL;
  SoupMessageHeaders *req_headers = NULL;
  SoupMessageHeaders *resp_headers = NULL;
  GBytes *body_bytes = NULL;
  GBytes *resp_bytes = NULL;
  GError *error = NULL;
  struct HttpResponse *new_res = NULL;
  int rc = 0;
  size_t i;
  void *payload = NULL;
  size_t payload_len = 0;
  const char *method_str;
  gsize resp_len = 0;
  gconstpointer resp_data = NULL;
  char *response_body_copy = NULL;

  if (!ctx || !ctx->session || !req || !res)
    return EINVAL;

  payload = req->body;
  payload_len = req->body_len;

  if (req->parts.count > 0 && !payload) {
    return EINVAL;
  }

  method_str = math_get_method_string(req->method);
  msg = soup_message_new(method_str, req->url);
  if (!msg) {
    return EINVAL; /* Bad URL likely */
  }

  req_headers = soup_message_get_request_headers(msg);
  for (i = 0; i < req->headers.count; ++i) {
    soup_message_headers_append(req_headers, req->headers.headers[i].key,
                                req->headers.headers[i].value);
  }

  if (payload && payload_len > 0) {
    /* Note: if chunked upload is needed, we would use
       soup_message_set_request_body with an input stream. For now, simple byte
       buffer upload. */
    body_bytes = g_bytes_new(payload, payload_len);
    soup_message_set_request_body_from_bytes(msg, NULL, body_bytes);
    g_bytes_unref(body_bytes);
  } else if (req->read_chunk) {
    /* Fallback for chunked upload without input stream: not fully supported in
     * this simplified binding */
    rc = ENOTSUP;
    goto cleanup;
  }

  resp_bytes = soup_session_send_and_read(ctx->session, msg, NULL, &error);

  if (error) {
    if (g_error_matches(error, G_IO_ERROR, G_IO_ERROR_CONNECTION_REFUSED)) {
      rc = ECONNREFUSED;
    } else if (g_error_matches(error, G_IO_ERROR, G_IO_ERROR_TIMED_OUT)) {
      rc = ETIMEDOUT;
    } else {
      rc = EIO;
    }
    goto cleanup;
  }

  new_res = (struct HttpResponse *)calloc(1, sizeof(struct HttpResponse));
  if (!new_res) {
    rc = ENOMEM;
    goto cleanup;
  }

  if (http_response_init(new_res) != 0) {
    free(new_res);
    rc = ENOMEM;
    goto cleanup;
  }

  new_res->status_code = soup_message_get_status(msg);

  if (resp_bytes) {
    resp_data = g_bytes_get_data(resp_bytes, &resp_len);
    if (resp_data && resp_len > 0) {
      if (req->on_chunk) {
        /* If streaming was requested, simulate it here via callback since we
         * fetched everything */
        int chunk_rc =
            req->on_chunk(req->on_chunk_user_data, resp_data, resp_len);
        if (chunk_rc != 0) {
          rc = ECANCELED; /* User aborted */
          free(new_res);
          new_res = NULL;
          goto cleanup;
        }
        /* When chunked, no body is kept */
        new_res->body = NULL;
        new_res->body_len = 0;
      } else {
        response_body_copy = (char *)malloc(resp_len + 1);
        if (!response_body_copy) {
          free(new_res);
          rc = ENOMEM;
          goto cleanup;
        }
        memcpy(response_body_copy, resp_data, resp_len);
        response_body_copy[resp_len] = '\0';
        new_res->body = response_body_copy;
        new_res->body_len = resp_len;
      }
    }
  }

  *res = new_res;

cleanup:
  if (error)
    g_error_free(error);
  if (resp_bytes)
    g_bytes_unref(resp_bytes);
  if (msg)
    g_object_unref(msg);

  return rc;
}
