/**
 * @file http_types.c
 * @brief Implementation of HTTP types lifecycle and Multipart Logic.
 * @author Samuel Marks
 */

/* clang-format off */
#include <ctype.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#if defined(_WIN32)
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#ifndef _WINSOCK_DEPRECATED_NO_WARNINGS
#define _WINSOCK_DEPRECATED_NO_WARNINGS
#endif
#include <winsock2.h>
#include <ws2tcpip.h>
#else
#if !defined(__MSDOS__) && !defined(__DOS__) && !defined(DOS)
#include <arpa/inet.h>
#include <netinet/in.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <unistd.h>
#endif
#endif

#include <c_abstract_http/http_types.h>
#include <c_abstract_http/str.h>

#include <stdarg.h>

/* clang-format on */
static /**
        * @brief Case-insensitive string comparison helper
        */
    int
    strcasecmp_portable(const char *s1, const char *s2, int *out_diff) {
  if (!out_diff)
    return EINVAL;
  if (!s1 || !s2) {
    *out_diff = -1;
    return EINVAL;
  }
  while (*s1 && *s2) {
    int diff = tolower((unsigned char)*s1) - tolower((unsigned char)*s2);
    if (diff != 0) {
      *out_diff = diff;
      return 0;
    }
    s1++;
    s2++;
  }
  *out_diff = tolower((unsigned char)*s1) - tolower((unsigned char)*s2);
  return 0;
}

static /**
        * @brief Autogenerated docstring
        */
    int
    sprintf_s_wrapper(char *buf, size_t start, size_t cap, const char *fmt,
                      ...) {
  int written;
  va_list args;
  va_start(args, fmt);
#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
  written = vsprintf_s(buf + start, cap - start, fmt, args);
#else
  (void)cap; /* Unused in C89 fallback */
  written = vsprintf(buf + start, fmt, args);
#endif
  va_end(args);
  return written;
}

/** @brief http_headers_init definition */
/**
 * @brief Autogenerated docstring
 */
int http_headers_init(struct HttpHeaders *headers) {
  if (!headers)
    return EINVAL;
  headers->headers = NULL;
  headers->count = 0;
  headers->capacity = 0;
  return 0;
}

/** @brief http_headers_free definition */
/**
 * @brief Autogenerated docstring
 */
void http_headers_free(struct HttpHeaders *headers) {
  size_t i;
  if (!headers)
    return;

  if (headers->headers) {
    for (i = 0; i < headers->count; ++i) {
      if (headers->headers[i].key)
        free(headers->headers[i].key);
      if (headers->headers[i].value)
        free(headers->headers[i].value);
    }
    free(headers->headers);
    headers->headers = NULL;
  }
  headers->count = 0;
  headers->capacity = 0;
}

/** @brief http_headers_add definition */
/**
 * @brief Autogenerated docstring
 */
int http_headers_add(struct HttpHeaders *headers, const char *key,
                     const char *value) {
  char *_ast_strdup_0 = NULL;
  char *_ast_strdup_1 = NULL;
  if (!headers || !key || !value)
    return EINVAL;

  if (headers->count >= headers->capacity) {
    const size_t new_cap = (headers->capacity == 0) ? 8 : headers->capacity * 2;
    struct HttpHeader *new_arr = (struct HttpHeader *)realloc(
        headers->headers, new_cap * sizeof(struct HttpHeader));
    if (!new_arr)
      return ENOMEM;
    headers->headers = new_arr;
    headers->capacity = new_cap;
  }

  headers->headers[headers->count].key =
      (c_cdd_strdup(key, &_ast_strdup_0), _ast_strdup_0);
  if (!headers->headers[headers->count].key)
    return ENOMEM;

  headers->headers[headers->count].value =
      (c_cdd_strdup(value, &_ast_strdup_1), _ast_strdup_1);
  if (!headers->headers[headers->count].value) {
    free(headers->headers[headers->count].key);
    return ENOMEM;
  }

  headers->count++;
  return 0;
}

/**
 * @brief Retrieves the value for a specific header key.
 */
int http_headers_get(const struct HttpHeaders *headers, const char *key,
                     const char **out) {
  size_t i;
  if (!headers || !key || !out)
    return EINVAL;

  for (i = 0; i < headers->count; ++i) {
    int diff = -1;
    if (strcasecmp_portable(headers->headers[i].key, key, &diff) == 0 &&
        diff == 0) {
      *out = headers->headers[i].value;
      return 0;
    }
  }
  return ENOENT;
}
/**
 * @brief Removes a header by key.
 */
int http_headers_remove(struct HttpHeaders *headers, const char *key) {
  size_t i, j;
  int found = 0;

  if (!headers || !key)
    return EINVAL;

  for (i = 0; i < headers->count;) {
    int diff = -1;
    if (strcasecmp_portable(headers->headers[i].key, key, &diff) == 0 &&
        diff == 0) {
      /* Free memory */
      free(headers->headers[i].key);
      free(headers->headers[i].value);

      /* Shift remaining elements left */
      for (j = i; j < headers->count - 1; ++j) {
        headers->headers[j] = headers->headers[j + 1];
      }

      headers->count--;
      found = 1;
      /* Do not increment i, as we need to check the shifted element */
    } else {
      i++;
    }
  }

  return found ? 0 : ENOENT;
}

/* --- Multipart Implementation --- */

/**
 * @brief Autogenerated docstring
 */
int http_parts_init(struct HttpParts *parts) {
  if (!parts)
    return EINVAL;
  parts->parts = NULL;
  parts->count = 0;
  parts->capacity = 0;
  return 0;
}

/**
 * @brief Autogenerated docstring
 */
void http_parts_free(struct HttpParts *parts) {
  size_t i;
  if (!parts)
    return;
  if (parts->parts) {
    for (i = 0; i < parts->count; ++i) {
      if (parts->parts[i].name)
        free(parts->parts[i].name);
      if (parts->parts[i].filename)
        free(parts->parts[i].filename);
      if (parts->parts[i].content_type)
        free(parts->parts[i].content_type);
      http_headers_free(&parts->parts[i].headers);
      /* data ownership is typically external references for efficiency,
         but for safety in this generator we assume data pointers are managed
         by the source (e.g. read_to_file or literal).
         The generic part struct doesn't own data memory. */
    }
    free(parts->parts);
    parts->parts = NULL;
  }
  parts->count = 0;
  parts->capacity = 0;
}

/**
 * @brief Autogenerated docstring
 */
int http_request_add_part(struct HttpRequest *req, const char *name,
                          const char *filename, const char *content_type,
                          const void *data, size_t data_len) {
  char *_ast_strdup_2 = NULL;
  char *_ast_strdup_3 = NULL;
  char *_ast_strdup_4 = NULL;
  struct HttpParts *p;
  if (!req || !name || (!data && data_len > 0))
    return EINVAL;

  p = &req->parts;
  if (p->count >= p->capacity) {
    size_t new_cap = (p->capacity == 0) ? 4 : p->capacity * 2;
    struct HttpPart *new_arr =
        (struct HttpPart *)realloc(p->parts, new_cap * sizeof(struct HttpPart));
    if (!new_arr)
      return ENOMEM;
    p->parts = new_arr;
    p->capacity = new_cap;
  }

  /* Zero new slot */
  memset(&p->parts[p->count], 0, sizeof(struct HttpPart));
  if (http_headers_init(&p->parts[p->count].headers) != 0)
    return EINVAL;

  p->parts[p->count].name = (c_cdd_strdup(name, &_ast_strdup_2), _ast_strdup_2);
  if (!p->parts[p->count].name) {
    http_headers_free(&p->parts[p->count].headers);
    return ENOMEM;
  }

  if (filename) {
    p->parts[p->count].filename =
        (c_cdd_strdup(filename, &_ast_strdup_3), _ast_strdup_3);
    if (!p->parts[p->count].filename) {
      free(p->parts[p->count].name);
      http_headers_free(&p->parts[p->count].headers);
      return ENOMEM;
    }
  }

  if (content_type) {
    p->parts[p->count].content_type =
        (c_cdd_strdup(content_type, &_ast_strdup_4), _ast_strdup_4);
    if (!p->parts[p->count].content_type) {
      if (p->parts[p->count].filename)
        free(p->parts[p->count].filename);
      free(p->parts[p->count].name);
      http_headers_free(&p->parts[p->count].headers);
      return ENOMEM;
    }
  }

  /* Reference data, do not copy yet. Serialization will copy. */
  p->parts[p->count].data = (void *)data;
  p->parts[p->count].data_len = data_len;

  p->count++;
  return 0;
}

/**
 * @brief Autogenerated docstring
 */
int http_request_add_part_header_last(struct HttpRequest *req, const char *key,
                                      const char *value) {
  struct HttpPart *part;
  if (!req || !key || !value)
    return EINVAL;
  if (req->parts.count == 0)
    return EINVAL;
  part = &req->parts.parts[req->parts.count - 1];
  return http_headers_add(&part->headers, key, value);
}

/**
 * @brief Autogenerated docstring
 */
int http_request_flatten_parts(struct HttpRequest *req) {
  char boundary[64];
  size_t i;
  size_t estimated_size = 0;
  char *buffer = NULL;
  size_t pos = 0;

  if (!req || req->parts.count == 0)
    return 0; /* Nothing to flatten */

  /* 1. Generate Boundary */
  if (req->body) {
    /* Already have a body, parts would conflict. Fail or warn? */
    return EINVAL;
  }

  srand((unsigned int)time(NULL));
#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
  sprintf_s(boundary, sizeof(boundary), "------------------------cddbound%08x",
            rand());
#else
  sprintf(boundary, "------------------------cddbound%08x", rand());
#endif

  /* 2. Calculate Size */
  for (i = 0; i < req->parts.count; ++i) {
    struct HttpPart *part = &req->parts.parts[i];
    size_t h;

    estimated_size += strlen(boundary) + 6; /* --bound\r\n */
    /* Content-Disposition: form-data; name="..." */
    estimated_size += 38 + strlen(part->name) + 4;
    if (part->filename) {
      /* ; filename="..." */
      estimated_size += 13 + strlen(part->filename) + 1;
    }
    estimated_size += 2; /* \r\n */

    if (part->content_type) {
      /* Content-Type: ...\r\n */
      estimated_size += 14 + strlen(part->content_type) + 2;
    } else if (part->filename) {
      /* Default to octet-stream for files */
      estimated_size +=
          14 + 24 + 2; /* Content-Type: application/octet-stream\r\n */
    }

    for (h = 0; h < part->headers.count; ++h) {
      const struct HttpHeader *hdr = &part->headers.headers[h];
      if (!hdr->key || !hdr->value)
        continue;
      estimated_size += strlen(hdr->key) + 2 + strlen(hdr->value) + 2;
    }

    estimated_size += 2; /* \r\n (end of headers) */
    estimated_size += part->data_len;
    estimated_size += 2; /* \r\n (end of part) */
  }
  estimated_size += strlen(boundary) + 8; /* --bound--\r\n\0 */

  /* 3. Build Buffer */
  buffer = (char *)malloc(estimated_size);
  if (!buffer)
    return ENOMEM;

  for (i = 0; i < req->parts.count; ++i) {
    struct HttpPart *part = &req->parts.parts[i];
    size_t h;
    int written;

    /* Boundary start */
    /* Note: Using sprintf directly is unsafe if we didn't pre-calc, assume size
     * is ok */
    /* Using safe wrapper logic */
    /* --boundary\r\n */
    written =
        sprintf_s_wrapper(buffer, pos, estimated_size, "--%s\r\n", boundary);
    pos += written;

    /* Header */
    written = sprintf_s_wrapper(buffer, pos, estimated_size,
                                "Content-Disposition: form-data; name=\"%s\"",
                                part->name);
    pos += written;

    if (part->filename) {
      written = sprintf_s_wrapper(buffer, pos, estimated_size,
                                  "; filename=\"%s\"", part->filename);
      pos += written;
    }
    written = sprintf_s_wrapper(buffer, pos, estimated_size, "\r\n");
    pos += written;

    /* Content-Type */
    if (part->content_type) {
      written = sprintf_s_wrapper(buffer, pos, estimated_size,
                                  "Content-Type: %s\r\n", part->content_type);
      pos += written;
    } else if (part->filename) {
      written = sprintf_s_wrapper(buffer, pos, estimated_size,
                                  "Content-Type: application/octet-stream\r\n");
      pos += written;
    }

    for (h = 0; h < part->headers.count; ++h) {
      const struct HttpHeader *hdr = &part->headers.headers[h];
      if (!hdr->key || !hdr->value)
        continue;
      written = sprintf_s_wrapper(buffer, pos, estimated_size, "%s: %s\r\n",
                                  hdr->key, hdr->value);
      pos += written;
    }

    /* End of headers */
    written = sprintf_s_wrapper(buffer, pos, estimated_size, "\r\n");
    pos += written;

    /* Data */
    if (part->data_len > 0 && part->data) {
      memcpy(buffer + pos, part->data, part->data_len);
      pos += part->data_len;
    }

    /* End of part */
    written = sprintf_s_wrapper(buffer, pos, estimated_size, "\r\n");
    pos += written;
  }

  /* Final Boundary */
  {
    int written =
        sprintf_s_wrapper(buffer, pos, estimated_size, "--%s--\r\n", boundary);
    pos += written;
  }

  /* 4. Update Request */
  req->body = buffer;
  req->body_len = pos;

  {
    char ct[128];
#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
    sprintf_s(ct, sizeof(ct), "multipart/form-data; boundary=%s", boundary);
#else
    sprintf(ct, "multipart/form-data; boundary=%s", boundary);
#endif
    /* If header exists, this adds a duplicate. Typically client code shouldn't
     * set CT if using parts. */
    http_headers_add(&req->headers, "Content-Type", ct);
  }

  /* 5. Clear parts logic to avoid double-process (though body takes precedence)
   */
  /* We don't free the parts struct itself as caller might own data, but we
   * effectively consumed it into body */

  return 0;
}

/**
 * @brief Initialize a cookie jar.
 */
int http_cookie_jar_init(struct HttpCookieJar *jar) {
  if (!jar)
    return EINVAL;
  jar->cookies = NULL;
  jar->count = 0;
  jar->capacity = 0;
  return 0;
}

/**
 * @brief Free resources held by a cookie jar.
 */
void http_cookie_jar_free(struct HttpCookieJar *jar) {
  size_t i;
  if (!jar)
    return;
  if (jar->cookies) {
    for (i = 0; i < jar->count; ++i) {
      if (jar->cookies[i].name)
        free(jar->cookies[i].name);
      if (jar->cookies[i].value)
        free(jar->cookies[i].value);
      if (jar->cookies[i].domain)
        free(jar->cookies[i].domain);
      if (jar->cookies[i].path)
        free(jar->cookies[i].path);
    }
    free(jar->cookies);
    jar->cookies = NULL;
  }
  jar->count = 0;
  jar->capacity = 0;
}

/**
 * @brief Add or update a cookie in the jar.
 */
int http_cookie_jar_set(struct HttpCookieJar *jar, const char *name,
                        const char *value) {
  char *_ast_strdup_cname = NULL;
  char *_ast_strdup_cval = NULL;
  size_t i;

  if (!jar || !name || !value)
    return EINVAL;

  /* Check for existing */
  for (i = 0; i < jar->count; ++i) {
    if (strcmp(jar->cookies[i].name, name) == 0) {
      char *new_val =
          (c_cdd_strdup(value, &_ast_strdup_cval), _ast_strdup_cval);
      if (!new_val)
        return ENOMEM;
      free(jar->cookies[i].value);
      jar->cookies[i].value = new_val;
      return 0;
    }
  }

  /* Insert new */
  if (jar->count >= jar->capacity) {
    size_t new_cap = (jar->capacity == 0) ? 4 : jar->capacity * 2;
    struct HttpCookie *new_arr = (struct HttpCookie *)realloc(
        jar->cookies, new_cap * sizeof(struct HttpCookie));
    if (!new_arr)
      return ENOMEM;
    jar->cookies = new_arr;
    jar->capacity = new_cap;
  }

  memset(&jar->cookies[jar->count], 0, sizeof(struct HttpCookie));

  jar->cookies[jar->count].name =
      (c_cdd_strdup(name, &_ast_strdup_cname), _ast_strdup_cname);
  if (!jar->cookies[jar->count].name)
    return ENOMEM;

  jar->cookies[jar->count].value =
      (c_cdd_strdup(value, &_ast_strdup_cval), _ast_strdup_cval);
  if (!jar->cookies[jar->count].value) {
    free(jar->cookies[jar->count].name);
    return ENOMEM;
  }

  jar->count++;
  return 0;
}

/**
 * @brief Get a cookie value from the jar.
 */
int http_cookie_jar_get(const struct HttpCookieJar *jar, const char *name,
                        const char **out) {
  size_t i;
  if (!jar || !name || !out)
    return EINVAL;
  for (i = 0; i < jar->count; ++i) {
    if (strcmp(jar->cookies[i].name, name) == 0) {
      *out = jar->cookies[i].value;
      return 0;
    }
  }
  return ENOENT;
}

/** @brief http_config_init definition */
/**
 * @brief Autogenerated docstring
 */
int http_config_init(struct HttpConfig *config) {
  char *_ast_strdup_5 = NULL;
  if (!config)
    return EINVAL;

  config->timeout_ms = 30000;
  config->connect_timeout_ms = 0;
  config->read_timeout_ms = 0;
  config->write_timeout_ms = 0;
  config->verify_peer = 1;
  config->verify_host = 1;
  config->follow_redirects = 1;
  config->proxy_url = NULL;
  config->proxy_username = NULL;
  config->proxy_password = NULL;
  config->cookie_jar = NULL;
  config->user_agent =
      (c_cdd_strdup("c_cdd/0.1.0", &_ast_strdup_5), _ast_strdup_5);

  /* Retry defaults */
  config->retry_count = 0;
  config->retry_policy = HTTP_RETRY_NONE;

  config->modality = MODALITY_SYNC;
  config->min_threads = 4;
  config->max_threads = 16;
  config->version_mask = HTTP_VERSION_DEFAULT;
  config->tls_version_mask = HTTP_TLS_VERSION_DEFAULT;
  config->http3_fallback = 1;

  if (!config->user_agent)
    return ENOMEM;

  return 0;
}

/** @brief http_config_free definition */
/**
 * @brief Autogenerated docstring
 */
void http_config_free(struct HttpConfig *config) {
  if (!config)
    return;
  if (config->user_agent) {
    free(config->user_agent);
    config->user_agent = NULL;
  }
  if (config->proxy_url) {
    free(config->proxy_url);
    config->proxy_url = NULL;
  }
  if (config->proxy_username) {
    free(config->proxy_username);
    config->proxy_username = NULL;
  }
  if (config->proxy_password) {
    free(config->proxy_password);
    config->proxy_password = NULL;
  }
}

/** @brief http_client_init definition */
/**
 * @brief Autogenerated docstring
 */
int http_client_init(struct HttpClient *client) {
  if (!client)
    return EINVAL;

  memset(client, 0, sizeof(struct HttpClient));
  return http_config_init(&client->config);
}

/** @brief http_client_free definition */
/**
 * @brief Autogenerated docstring
 */
void http_client_free(struct HttpClient *client) {
  if (!client)
    return;

  http_config_free(&client->config);

  if (client->base_url) {
    free(client->base_url);
    client->base_url = NULL;
  }
}

/** @brief http_request_init definition */
/**
 * @brief Autogenerated docstring
 */
int http_request_init(struct HttpRequest *req) {
  if (!req)
    return EINVAL;
  req->url = NULL;
  req->method = HTTP_GET;
  req->body = NULL;
  req->body_len = 0;
  req->on_chunk = NULL;
  req->on_chunk_user_data = NULL;
  req->read_chunk = NULL;
  req->read_chunk_user_data = NULL;
  req->expected_body_len = 0;
  if (http_headers_init(&req->headers) != 0)
    return ENOMEM;
  if (http_parts_init(&req->parts) != 0) {
    http_headers_free(&req->headers);
    return ENOMEM;
  }
  return 0;
}

/** @brief http_request_free definition */
/**
 * @brief Autogenerated docstring
 */
void http_request_free(struct HttpRequest *req) {
  if (!req)
    return;
  if (req->url) {
    free(req->url);
    req->url = NULL;
  }
  if (req->body) {
    free(req->body);
    req->body = NULL;
  }
  http_headers_free(&req->headers);
  http_parts_free(&req->parts);
}

int http_modality_context_init(struct ModalityContext *ctx) {
  if (!ctx)
    return EINVAL;
  ctx->modality = MODALITY_SYNC;
  ctx->internal_ctx = NULL;
  return 0;
}

void http_modality_context_free(struct ModalityContext *ctx) {
  if (!ctx)
    return;
  /* Modality specific cleanup would happen here later */
  ctx->internal_ctx = NULL;
}

int http_future_init(struct HttpFuture *future) {
  if (!future)
    return EINVAL;
  future->is_ready = 0;
  future->error_code = 0;
  future->response = NULL;
  future->internal_state = NULL;
  return 0;
}

void http_future_free(struct HttpFuture *future) {
  if (!future)
    return;
  /* if we owned future->response, we might free it, but usually user takes
   * ownership */
  future->response = NULL;
  future->internal_state = NULL;
}

int http_multi_request_init(struct HttpMultiRequest *multi) {
  if (!multi)
    return EINVAL;
  multi->requests = NULL;
  multi->count = 0;
  multi->capacity = 0;
  return 0;
}

void http_multi_request_free(struct HttpMultiRequest *multi) {
  if (!multi)
    return;
  if (multi->requests) {
    /* Does not free the actual HttpRequest objects, just the array */
    free(multi->requests);
    multi->requests = NULL;
  }
  multi->count = 0;
  multi->capacity = 0;
}

int http_multi_request_add(struct HttpMultiRequest *multi,
                           struct HttpRequest *req) {
  if (!multi || !req)
    return EINVAL;

  if (multi->count >= multi->capacity) {
    size_t new_cap = (multi->capacity == 0) ? 4 : multi->capacity * 2;
    struct HttpRequest **new_arr = (struct HttpRequest **)realloc(
        multi->requests, new_cap * sizeof(struct HttpRequest *));
    if (!new_arr)
      return ENOMEM;
    multi->requests = new_arr;
    multi->capacity = new_cap;
  }

  multi->requests[multi->count++] = req;
  return 0;
}

/** @brief http_request_set_auth_bearer definition */
/**
 * @brief Autogenerated docstring
 */
int http_request_set_auth_bearer(struct HttpRequest *req, const char *token) {
  char *val = NULL;
  int rc;
  size_t len;

  if (!req || !token)
    return EINVAL;

  len = strlen(token) + 8;
  val = (char *)malloc(len);
  if (!val)
    return ENOMEM;

#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
  sprintf_s(val, len, "Bearer %s", token);
#else
  sprintf(val, "Bearer %s", token);
#endif

  rc = http_headers_add(&req->headers, "Authorization", val);
  free(val);

  return rc;
}

/**
 * @brief Autogenerated docstring
 */
int http_request_set_auth_basic(struct HttpRequest *req, const char *token) {
  char *val = NULL;
  int rc;
  size_t len;

  if (!req || !token)
    return EINVAL;

  len = strlen(token) + 7;
  val = (char *)malloc(len);
  if (!val)
    return ENOMEM;

#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
  sprintf_s(val, len, "Basic %s", token);
#else
  sprintf(val, "Basic %s", token);
#endif

  rc = http_headers_add(&req->headers, "Authorization", val);
  free(val);

  return rc;
}

/**
 * @brief Simple base64 encoder for basic auth
 */
static int base64_encode(const unsigned char *src, size_t len, char **out) {
  static const char b64[] =
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  char *res;
  size_t olen = 4 * ((len + 2) / 3);
  size_t i, j;
  if (!src || !out)
    return EINVAL;
  res = (char *)malloc(olen + 1);
  if (!res)
    return ENOMEM;

  for (i = 0, j = 0; i < len;) {
    unsigned int octet_a = i < len ? src[i++] : 0;
    unsigned int octet_b = i < len ? src[i++] : 0;
    unsigned int octet_c = i < len ? src[i++] : 0;
    unsigned int triple = (octet_a << 0x10) + (octet_b << 0x08) + octet_c;

    res[j++] = b64[(triple >> 3 * 6) & 0x3F];
    res[j++] = b64[(triple >> 2 * 6) & 0x3F];
    res[j++] = b64[(triple >> 1 * 6) & 0x3F];
    res[j++] = b64[(triple >> 0 * 6) & 0x3F];
  }

  if (len % 3 == 1) {
    res[olen - 1] = '=';
    res[olen - 2] = '=';
  } else if (len % 3 == 2) {
    res[olen - 1] = '=';
  }
  res[olen] = '\0';
  *out = res;
  return 0;
}

/**
 * @brief Autogenerated docstring
 */
int http_request_set_auth_basic_userpwd(struct HttpRequest *req,
                                        const char *username,
                                        const char *password) {
  char *raw;
  char *encoded = NULL;
  size_t len;
  int rc;
  if (!req || !username || !password)
    return EINVAL;

  len = strlen(username) + strlen(password) + 2;
  raw = (char *)malloc(len);
  if (!raw)
    return ENOMEM;

#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
  sprintf_s(raw, len, "%s:%s", username, password);
#else
  sprintf(raw, "%s:%s", username, password);
#endif

  rc = base64_encode((const unsigned char *)raw, len - 1, &encoded);
  free(raw);
  if (rc != 0)
    return rc;

  rc = http_request_set_auth_basic(req, encoded);
  free(encoded);

  return rc;
}

static size_t urlencode_len(const char *src) {
  size_t len = 0;
  const char *p;
  if (!src)
    return 0;
  for (p = src; *p; p++) {
    unsigned char c = (unsigned char)*p;
    if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
        (c >= '0' && c <= '9') || c == '-' || c == '_' || c == '.' ||
        c == '~') {
      len++;
    } else if (c == ' ') {
      len++;
    } else {
      len += 3;
    }
  }
  return len;
}

static void urlencode_append(char **dest, const char *src) {
  static const char *hex = "0123456789ABCDEF";
  const char *p;
  char *q = *dest;
  if (!src)
    return;
  for (p = src; *p; p++) {
    unsigned char c = (unsigned char)*p;
    if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
        (c >= '0' && c <= '9') || c == '-' || c == '_' || c == '.' ||
        c == '~') {
      *q++ = c;
    } else if (c == ' ') {
      *q++ = '+';
    } else {
      *q++ = '%';
      *q++ = hex[c >> 4];
      *q++ = hex[c & 15];
    }
  }
  *dest = q;
}

/**
 * @brief Autogenerated docstring
 */
int http_request_init_oauth2_password_grant(
    struct HttpRequest *req, const char *token_endpoint_url,
    const char *username, const char *password, const char *client_id,
    const char *client_secret, const char *scope) {
  size_t body_len = 0;
  char *body = NULL;
  char *p = NULL;
  int rc;
  const char *grant_type = "password";

  if (!req || !token_endpoint_url || !username || !password)
    return EINVAL;

  req->url = NULL;
  rc = c_cdd_strdup(token_endpoint_url, &req->url);
  if (rc != 0)
    return rc;

  req->method = HTTP_POST;

  rc = http_headers_add(&req->headers, "Content-Type",
                        "application/x-www-form-urlencoded");
  if (rc != 0)
    return rc;

  /* Calculate length */
  body_len += 11 + urlencode_len(grant_type); /* grant_type=... */
  body_len += 10 + urlencode_len(username);   /* &username=... */
  body_len += 10 + urlencode_len(password);   /* &password=... */

  if (client_id)
    body_len += 11 + urlencode_len(client_id); /* &client_id=... */
  if (client_secret)
    body_len += 15 + urlencode_len(client_secret); /* &client_secret=... */
  if (scope)
    body_len += 7 + urlencode_len(scope); /* &scope=... */

  body = (char *)malloc(body_len + 1);
  if (!body)
    return ENOMEM;

  p = body;
  /* grant_type=password */
  memcpy(p, "grant_type=", 11);
  p += 11;
  urlencode_append(&p, grant_type);

  /* &username=... */
  memcpy(p, "&username=", 10);
  p += 10;
  urlencode_append(&p, username);

  /* &password=... */
  memcpy(p, "&password=", 10);
  p += 10;
  urlencode_append(&p, password);

  if (client_id) {
    memcpy(p, "&client_id=", 11);
    p += 11;
    urlencode_append(&p, client_id);
  }

  if (client_secret) {
    memcpy(p, "&client_secret=", 15);
    p += 15;
    urlencode_append(&p, client_secret);
  }

  if (scope) {
    memcpy(p, "&scope=", 7);
    p += 7;
    urlencode_append(&p, scope);
  }

  *p = '\0';
  req->body = body;
  req->body_len = body_len;

  return 0;
}

/**
 * @brief Autogenerated docstring
 */
int http_request_init_oauth2_refresh_token_grant(struct HttpRequest *req,
                                                 const char *token_endpoint_url,
                                                 const char *refresh_token,
                                                 const char *client_id,
                                                 const char *client_secret,
                                                 const char *scope) {
  size_t body_len = 0;
  char *body = NULL;
  char *p = NULL;
  int rc;
  const char *grant_type = "refresh_token";

  if (!req || !token_endpoint_url || !refresh_token)
    return EINVAL;

  req->url = NULL;
  rc = c_cdd_strdup(token_endpoint_url, &req->url);
  if (rc != 0)
    return rc;

  req->method = HTTP_POST;

  rc = http_headers_add(&req->headers, "Content-Type",
                        "application/x-www-form-urlencoded");
  if (rc != 0)
    return rc;

  /* Calculate length */
  body_len += 11 + urlencode_len(grant_type);    /* grant_type=... */
  body_len += 15 + urlencode_len(refresh_token); /* &refresh_token=... */

  if (client_id)
    body_len += 11 + urlencode_len(client_id); /* &client_id=... */
  if (client_secret)
    body_len += 15 + urlencode_len(client_secret); /* &client_secret=... */
  if (scope)
    body_len += 7 + urlencode_len(scope); /* &scope=... */

  body = (char *)malloc(body_len + 1);
  if (!body)
    return ENOMEM;

  p = body;
  /* grant_type=refresh_token */
  memcpy(p, "grant_type=", 11);
  p += 11;
  urlencode_append(&p, grant_type);

  /* &refresh_token=... */
  memcpy(p, "&refresh_token=", 15);
  p += 15;
  urlencode_append(&p, refresh_token);

  if (client_id) {
    memcpy(p, "&client_id=", 11);
    p += 11;
    urlencode_append(&p, client_id);
  }

  if (client_secret) {
    memcpy(p, "&client_secret=", 15);
    p += 15;
    urlencode_append(&p, client_secret);
  }

  if (scope) {
    memcpy(p, "&scope=", 7);
    p += 7;
    urlencode_append(&p, scope);
  }

  *p = '\0';
  req->body = body;
  req->body_len = body_len;

  return 0;
}

/**
 * @brief Autogenerated docstring
 */
int http_request_init_oauth2_authorization_code_grant(
    struct HttpRequest *req, const char *token_endpoint_url, const char *code,
    const char *redirect_uri, const char *client_id, const char *client_secret,
    const char *code_verifier) {
  size_t body_len = 0;
  char *body = NULL;
  char *p = NULL;
  int rc;
  const char *grant_type = "authorization_code";

  if (!req || !token_endpoint_url || !code)
    return EINVAL;

  req->url = NULL;
  rc = c_cdd_strdup(token_endpoint_url, &req->url);
  if (rc != 0)
    return rc;

  req->method = HTTP_POST;

  rc = http_headers_add(&req->headers, "Content-Type",
                        "application/x-www-form-urlencoded");
  if (rc != 0)
    return rc;

  /* Calculate length */
  body_len += 11 + urlencode_len(grant_type); /* grant_type=... */
  body_len += 6 + urlencode_len(code);        /* &code=... */

  if (redirect_uri)
    body_len += 14 + urlencode_len(redirect_uri); /* &redirect_uri=... */
  if (client_id)
    body_len += 11 + urlencode_len(client_id); /* &client_id=... */
  if (client_secret)
    body_len += 15 + urlencode_len(client_secret); /* &client_secret=... */
  if (code_verifier)
    body_len += 15 + urlencode_len(code_verifier); /* &code_verifier=... */

  body = (char *)malloc(body_len + 1);
  if (!body)
    return ENOMEM;

  p = body;
  /* grant_type=authorization_code */
  memcpy(p, "grant_type=", 11);
  p += 11;
  urlencode_append(&p, grant_type);

  /* &code=... */
  memcpy(p, "&code=", 6);
  p += 6;
  urlencode_append(&p, code);

  if (redirect_uri) {
    memcpy(p, "&redirect_uri=", 14);
    p += 14;
    urlencode_append(&p, redirect_uri);
  }

  if (client_id) {
    memcpy(p, "&client_id=", 11);
    p += 11;
    urlencode_append(&p, client_id);
  }

  if (client_secret) {
    memcpy(p, "&client_secret=", 15);
    p += 15;
    urlencode_append(&p, client_secret);
  }

  if (code_verifier) {
    memcpy(p, "&code_verifier=", 15);
    p += 15;
    urlencode_append(&p, code_verifier);
  }

  *p = '\0';
  req->body = body;
  req->body_len = body_len;

  return 0;
}

/**
 * @brief Autogenerated docstring
 */
int http_request_init_oauth2_client_credentials_grant(
    struct HttpRequest *req, const char *token_endpoint_url,
    const char *client_id, const char *client_secret, const char *scope) {
  size_t body_len = 0;
  char *body = NULL;
  char *p = NULL;
  int rc;
  const char *grant_type = "client_credentials";

  if (!req || !token_endpoint_url)
    return EINVAL;

  req->url = NULL;
  rc = c_cdd_strdup(token_endpoint_url, &req->url);
  if (rc != 0)
    return rc;

  req->method = HTTP_POST;

  rc = http_headers_add(&req->headers, "Content-Type",
                        "application/x-www-form-urlencoded");
  if (rc != 0)
    return rc;

  /* Calculate length */
  body_len += 11 + urlencode_len(grant_type); /* grant_type=... */

  if (client_id)
    body_len += 11 + urlencode_len(client_id); /* &client_id=... */
  if (client_secret)
    body_len += 15 + urlencode_len(client_secret); /* &client_secret=... */
  if (scope)
    body_len += 7 + urlencode_len(scope); /* &scope=... */

  body = (char *)malloc(body_len + 1);
  if (!body)
    return ENOMEM;

  p = body;
  /* grant_type=client_credentials */
  memcpy(p, "grant_type=", 11);
  p += 11;
  urlencode_append(&p, grant_type);

  if (client_id) {
    memcpy(p, "&client_id=", 11);
    p += 11;
    urlencode_append(&p, client_id);
  }

  if (client_secret) {
    memcpy(p, "&client_secret=", 15);
    p += 15;
    urlencode_append(&p, client_secret);
  }

  if (scope) {
    memcpy(p, "&scope=", 7);
    p += 7;
    urlencode_append(&p, scope);
  }

  *p = '\0';
  req->body = body;
  req->body_len = body_len;

  return 0;
}

/**
 * @brief Autogenerated docstring
 */
int http_request_init_oauth2_jwt_bearer_grant(struct HttpRequest *req,
                                              const char *token_endpoint_url,
                                              const char *assertion,
                                              const char *scope) {
  size_t body_len = 0;
  char *body = NULL;
  char *p = NULL;
  int rc;
  const char *grant_type = "urn:ietf:params:oauth:grant-type:jwt-bearer";

  if (!req || !token_endpoint_url || !assertion)
    return EINVAL;

  req->url = NULL;
  rc = c_cdd_strdup(token_endpoint_url, &req->url);
  if (rc != 0)
    return rc;

  req->method = HTTP_POST;

  rc = http_headers_add(&req->headers, "Content-Type",
                        "application/x-www-form-urlencoded");
  if (rc != 0)
    return rc;

  /* Calculate length */
  body_len += 11 + urlencode_len(grant_type); /* grant_type=... */
  body_len += 11 + urlencode_len(assertion);  /* &assertion=... */

  if (scope)
    body_len += 7 + urlencode_len(scope); /* &scope=... */

  body = (char *)malloc(body_len + 1);
  if (!body)
    return ENOMEM;

  p = body;
  /* grant_type=... */
  memcpy(p, "grant_type=", 11);
  p += 11;
  urlencode_append(&p, grant_type);

  /* &assertion=... */
  memcpy(p, "&assertion=", 11);
  p += 11;
  urlencode_append(&p, assertion);

  if (scope) {
    memcpy(p, "&scope=", 7);
    p += 7;
    urlencode_append(&p, scope);
  }

  *p = '\0';
  req->body = body;
  req->body_len = body_len;

  return 0;
}

/**
 * @brief Autogenerated docstring
 */
int http_request_init_oauth2_device_authorization_request(
    struct HttpRequest *req, const char *device_endpoint_url,
    const char *client_id, const char *scope) {
  size_t body_len = 0;
  char *body = NULL;
  char *p = NULL;
  int rc;

  if (!req || !device_endpoint_url || !client_id)
    return EINVAL;

  req->url = NULL;
  rc = c_cdd_strdup(device_endpoint_url, &req->url);
  if (rc != 0)
    return rc;

  req->method = HTTP_POST;

  rc = http_headers_add(&req->headers, "Content-Type",
                        "application/x-www-form-urlencoded");
  if (rc != 0)
    return rc;

  body_len += 10 + urlencode_len(client_id); /* client_id=... */
  if (scope)
    body_len += 7 + urlencode_len(scope); /* &scope=... */

  body = (char *)malloc(body_len + 1);
  if (!body)
    return ENOMEM;

  p = body;
  memcpy(p, "client_id=", 10);
  p += 10;
  urlencode_append(&p, client_id);

  if (scope) {
    memcpy(p, "&scope=", 7);
    p += 7;
    urlencode_append(&p, scope);
  }

  *p = '\0';
  req->body = body;
  req->body_len = body_len;

  return 0;
}

/**
 * @brief Autogenerated docstring
 */
int http_request_init_oauth2_device_access_token_request(
    struct HttpRequest *req, const char *token_endpoint_url,
    const char *client_id, const char *device_code) {
  size_t body_len = 0;
  char *body = NULL;
  char *p = NULL;
  int rc;
  const char *grant_type = "urn:ietf:params:oauth:grant-type:device_code";

  if (!req || !token_endpoint_url || !client_id || !device_code)
    return EINVAL;

  req->url = NULL;
  rc = c_cdd_strdup(token_endpoint_url, &req->url);
  if (rc != 0)
    return rc;

  req->method = HTTP_POST;

  rc = http_headers_add(&req->headers, "Content-Type",
                        "application/x-www-form-urlencoded");
  if (rc != 0)
    return rc;

  body_len += 11 + urlencode_len(grant_type);  /* grant_type=... */
  body_len += 11 + urlencode_len(client_id);   /* &client_id=... */
  body_len += 13 + urlencode_len(device_code); /* &device_code=... */

  body = (char *)malloc(body_len + 1);
  if (!body)
    return ENOMEM;

  p = body;
  memcpy(p, "grant_type=", 11);
  p += 11;
  urlencode_append(&p, grant_type);

  memcpy(p, "&client_id=", 11);
  p += 11;
  urlencode_append(&p, client_id);

  memcpy(p, "&device_code=", 13);
  p += 13;
  urlencode_append(&p, device_code);

  *p = '\0';
  req->body = body;
  req->body_len = body_len;

  return 0;
}

/**
 * @brief Autogenerated docstring
 */
int http_request_init_oauth2_token_revocation(
    struct HttpRequest *req, const char *revocation_endpoint_url,
    const char *token, const char *token_type_hint, const char *client_id,
    const char *client_secret) {
  size_t body_len = 0;
  char *body = NULL;
  char *p = NULL;
  int rc;

  if (!req || !revocation_endpoint_url || !token)
    return EINVAL;

  req->url = NULL;
  rc = c_cdd_strdup(revocation_endpoint_url, &req->url);
  if (rc != 0)
    return rc;

  req->method = HTTP_POST;

  rc = http_headers_add(&req->headers, "Content-Type",
                        "application/x-www-form-urlencoded");
  if (rc != 0)
    return rc;

  body_len += 6 + urlencode_len(token); /* token=... */

  if (token_type_hint)
    body_len += 17 + urlencode_len(token_type_hint); /* &token_type_hint=... */
  if (client_id)
    body_len += 11 + urlencode_len(client_id); /* &client_id=... */
  if (client_secret)
    body_len += 15 + urlencode_len(client_secret); /* &client_secret=... */

  body = (char *)malloc(body_len + 1);
  if (!body)
    return ENOMEM;

  p = body;
  memcpy(p, "token=", 6);
  p += 6;
  urlencode_append(&p, token);

  if (token_type_hint) {
    memcpy(p, "&token_type_hint=", 17);
    p += 17;
    urlencode_append(&p, token_type_hint);
  }

  if (client_id) {
    memcpy(p, "&client_id=", 11);
    p += 11;
    urlencode_append(&p, client_id);
  }

  if (client_secret) {
    memcpy(p, "&client_secret=", 15);
    p += 15;
    urlencode_append(&p, client_secret);
  }

  *p = '\0';
  req->body = body;
  req->body_len = body_len;

  return 0;
}

/**
 * @brief Autogenerated docstring
 */
int http_request_init_oauth2_token_introspection(
    struct HttpRequest *req, const char *introspection_endpoint_url,
    const char *token, const char *token_type_hint, const char *client_id,
    const char *client_secret) {
  size_t body_len = 0;
  char *body = NULL;
  char *p = NULL;
  int rc;

  if (!req || !introspection_endpoint_url || !token)
    return EINVAL;

  req->url = NULL;
  rc = c_cdd_strdup(introspection_endpoint_url, &req->url);
  if (rc != 0)
    return rc;

  req->method = HTTP_POST;

  rc = http_headers_add(&req->headers, "Content-Type",
                        "application/x-www-form-urlencoded");
  if (rc != 0)
    return rc;

  body_len += 6 + urlencode_len(token); /* token=... */

  if (token_type_hint)
    body_len += 17 + urlencode_len(token_type_hint); /* &token_type_hint=... */
  if (client_id)
    body_len += 11 + urlencode_len(client_id); /* &client_id=... */
  if (client_secret)
    body_len += 15 + urlencode_len(client_secret); /* &client_secret=... */

  body = (char *)malloc(body_len + 1);
  if (!body)
    return ENOMEM;

  p = body;
  memcpy(p, "token=", 6);
  p += 6;
  urlencode_append(&p, token);

  if (token_type_hint) {
    memcpy(p, "&token_type_hint=", 17);
    p += 17;
    urlencode_append(&p, token_type_hint);
  }

  if (client_id) {
    memcpy(p, "&client_id=", 11);
    p += 11;
    urlencode_append(&p, client_id);
  }

  if (client_secret) {
    memcpy(p, "&client_secret=", 15);
    p += 15;
    urlencode_append(&p, client_secret);
  }

  *p = '\0';
  req->body = body;
  req->body_len = body_len;

  return 0;
}

/**
 * @brief Autogenerated docstring
 */
int http_oauth2_build_authorization_url(
    const char *auth_endpoint, const char *client_id, const char *response_type,
    const char *redirect_uri, const char *scope, const char *state,
    const char *code_challenge, const char *code_challenge_method,
    char **out_url) {
  size_t len = 0;
  char *url = NULL;
  char *p = NULL;
  int has_query = 0;

  if (!auth_endpoint || !client_id || !response_type || !out_url)
    return EINVAL;

  has_query = (strchr(auth_endpoint, '?') != NULL) ? 1 : 0;

  len = strlen(auth_endpoint);
  len += 1 + 14 + urlencode_len(response_type); /* ?response_type=... */
  len += 11 + urlencode_len(client_id);         /* &client_id=... */

  if (redirect_uri)
    len += 14 + urlencode_len(redirect_uri); /* &redirect_uri=... */
  if (scope)
    len += 7 + urlencode_len(scope); /* &scope=... */
  if (state)
    len += 7 + urlencode_len(state); /* &state=... */
  if (code_challenge)
    len += 16 + urlencode_len(code_challenge); /* &code_challenge=... */
  if (code_challenge_method)
    len += 23 + urlencode_len(
                    code_challenge_method); /* &code_challenge_method=... */

  url = (char *)malloc(len + 1);
  if (!url)
    return ENOMEM;

  p = url;
  memcpy(p, auth_endpoint, strlen(auth_endpoint));
  p += strlen(auth_endpoint);

  *p++ = has_query ? '&' : '?';
  memcpy(p, "response_type=", 14);
  p += 14;
  urlencode_append(&p, response_type);

  memcpy(p, "&client_id=", 11);
  p += 11;
  urlencode_append(&p, client_id);

  if (redirect_uri) {
    memcpy(p, "&redirect_uri=", 14);
    p += 14;
    urlencode_append(&p, redirect_uri);
  }

  if (scope) {
    memcpy(p, "&scope=", 7);
    p += 7;
    urlencode_append(&p, scope);
  }

  if (state) {
    memcpy(p, "&state=", 7);
    p += 7;
    urlencode_append(&p, state);
  }

  if (code_challenge) {
    memcpy(p, "&code_challenge=", 16);
    p += 16;
    urlencode_append(&p, code_challenge);
  }

  if (code_challenge_method) {
    memcpy(p, "&code_challenge_method=", 23);
    p += 23;
    urlencode_append(&p, code_challenge_method);
  }

  *p = '\0';
  *out_url = url;

  return 0;
}

#if defined(_WIN32)
#define CDD_CLOSESOCKET closesocket
typedef SOCKET cdd_socket_t;
#define CDD_INVALID_SOCKET_VAL INVALID_SOCKET
#define CDD_SOCKET_ERROR_VAL SOCKET_ERROR
#else
#define CDD_CLOSESOCKET close
typedef int cdd_socket_t;
#define CDD_INVALID_SOCKET_VAL -1
#define CDD_SOCKET_ERROR_VAL -1
#endif

#if !defined(__MSDOS__) && !defined(__DOS__) && !defined(DOS)
static int urldecode_alloc(const char *src, size_t src_len, char **out) {
  char *dst = (char *)malloc(src_len + 1);
  size_t i, j = 0;
  if (!dst)
    return ENOMEM;
  for (i = 0; i < src_len; i++) {
    if (src[i] == '%') {
      if (i + 2 < src_len) {
        int a = (unsigned char)src[i + 1];
        int b = (unsigned char)src[i + 2];
        a = (a >= '0' && a <= '9') ? a - '0' : (tolower(a) - 'a' + 10);
        b = (b >= '0' && b <= '9') ? b - '0' : (tolower(b) - 'a' + 10);
        dst[j++] = (char)((a << 4) | b);
        i += 2;
      }
    } else if (src[i] == '+') {
      dst[j++] = ' ';
    } else {
      dst[j++] = src[i];
    }
  }
  dst[j] = '\0';
  *out = dst;
  return 0;
}
#endif

/**
 * @brief Autogenerated docstring
 */
int http_oauth2_localhost_intercept(unsigned short port,
                                    const char *html_response, char **out_code,
                                    char **out_state, char **out_error,
                                    char **out_error_desc) {
#if defined(__MSDOS__) || defined(__DOS__) || defined(DOS)
  (void)port;
  (void)html_response;
  if (out_code)
    *out_code = NULL;
  if (out_state)
    *out_state = NULL;
  if (out_error)
    *out_error = NULL;
  if (out_error_desc)
    *out_error_desc = NULL;
  return ENOTSUP;
#else
  cdd_socket_t srv_sock = CDD_INVALID_SOCKET_VAL,
               cli_sock = CDD_INVALID_SOCKET_VAL;
  struct sockaddr_in saddr;
  char buf[4096];
  int rc = 0, n;
  char *p;
  int opt = 1;

  if (out_code)
    *out_code = NULL;
  if (out_state)
    *out_state = NULL;
  if (out_error)
    *out_error = NULL;
  if (out_error_desc)
    *out_error_desc = NULL;

#if defined(_WIN32)
  {
    WSADATA wsa;
    if (WSAStartup(MAKEWORD(2, 2), &wsa) != 0)
      return EIO;
  }
#endif

  srv_sock = socket(AF_INET, SOCK_STREAM, 0);
  if (srv_sock == CDD_INVALID_SOCKET_VAL) {
    rc = EIO;
    goto cleanup;
  }

  setsockopt(srv_sock, SOL_SOCKET, SO_REUSEADDR, (const char *)&opt,
             sizeof(opt));

  memset(&saddr, 0, sizeof(saddr));
  saddr.sin_family = AF_INET;
  saddr.sin_port = htons(port);
  saddr.sin_addr.s_addr = inet_addr("127.0.0.1");

  if (bind(srv_sock, (struct sockaddr *)&saddr, sizeof(saddr)) ==
      CDD_SOCKET_ERROR_VAL) {
    rc = EIO;
    goto cleanup;
  }

  if (listen(srv_sock, 1) == CDD_SOCKET_ERROR_VAL) {
    rc = EIO;
    goto cleanup;
  }

  cli_sock = accept(srv_sock, NULL, NULL);
  if (cli_sock == CDD_INVALID_SOCKET_VAL) {
    rc = EIO;
    goto cleanup;
  }

  n = recv(cli_sock, buf, sizeof(buf) - 1, 0);
  if (n <= 0) {
    rc = EIO;
    goto cleanup;
  }
  buf[n] = '\0';

  if (html_response) {
    send(cli_sock, html_response, (int)strlen(html_response), 0);
  }

  if (strncmp(buf, "GET ", 4) != 0) {
    rc = EINVAL;
    goto cleanup;
  }

  p = buf + 4;
  while (*p && *p != '?' && *p != ' ' && *p != '\r' && *p != '\n')
    p++;
  if (*p == '?') {
    p++;
    while (*p && *p != ' ') {
      char *key = p;
      char *val = NULL;
      size_t key_len = 0;
      size_t val_len = 0;

      while (*p && *p != '=' && *p != '&' && *p != ' ')
        p++;
      key_len = p - key;

      if (*p == '=') {
        p++;
        val = p;
        while (*p && *p != '&' && *p != ' ')
          p++;
        val_len = p - val;
      }

      if (key_len == 4 && strncmp(key, "code", 4) == 0 && out_code && val) {
        if (urldecode_alloc(val, val_len, out_code) != 0)
          rc = ENOMEM;
      } else if (key_len == 5 && strncmp(key, "state", 5) == 0 && out_state &&
                 val) {
        if (urldecode_alloc(val, val_len, out_state) != 0)
          rc = ENOMEM;
      } else if (key_len == 5 && strncmp(key, "error", 5) == 0 && out_error &&
                 val) {
        if (urldecode_alloc(val, val_len, out_error) != 0)
          rc = ENOMEM;
      } else if (key_len == 17 && strncmp(key, "error_description", 17) == 0 &&
                 out_error_desc && val) {
        if (urldecode_alloc(val, val_len, out_error_desc) != 0)
          rc = ENOMEM;
      }

      if (*p == '&')
        p++;
    }
  }

cleanup:
  if (cli_sock != CDD_INVALID_SOCKET_VAL)
    CDD_CLOSESOCKET(cli_sock);
  if (srv_sock != CDD_INVALID_SOCKET_VAL)
    CDD_CLOSESOCKET(srv_sock);
#if defined(_WIN32)
  WSACleanup();
#endif
  return rc;
#endif
}

/** @brief http_response_init definition */
/**
 * @brief Autogenerated docstring
 */
int http_response_init(struct HttpResponse *res) {
  if (!res)
    return EINVAL;
  res->status_code = 0;
  res->body = NULL;
  res->body_len = 0;
  return http_headers_init(&res->headers);
}

/** @brief http_response_free definition */
/**
 * @brief Autogenerated docstring
 */
void http_response_free(struct HttpResponse *res) {
  if (!res)
    return;
  if (res->body) {
    free(res->body);
    res->body = NULL;
  }
  http_headers_free(&res->headers);
}

/** @brief http_response_save_to_file definition */
/**
 * @brief Autogenerated docstring
 */
int http_response_save_to_file(const struct HttpResponse *res,
                               const char *path) {
  FILE *f = NULL;
  size_t written;

  if (!res || !path)
    return EINVAL;

  if (!res->body && res->body_len > 0)
    return EINVAL;

#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
  if (fopen_s(&f, path, "wb") != 0)
    return EIO;
#else
#if defined(_MSC_VER)
  fopen_s(&f, path, "wb");
#else
#if defined(_MSC_VER)
  fopen_s(&f, path, "wb");
#else
#if defined(_MSC_VER)
  fopen_s(&f, path, "wb");
#else
#if defined(_MSC_VER)
  fopen_s(&f, path, "wb");
#else
#if defined(_MSC_VER)
  fopen_s(&f, path, "wb");
#else
  f = fopen(path, "wb");
#endif
#endif
#endif
#endif
#endif
  if (!f)
    return errno ? errno : EIO;
#endif

  if (res->body_len > 0 && res->body) {
    written = fwrite(res->body, 1, res->body_len, f);
    if (written != res->body_len) {
      fclose(f);
      return EIO;
    }
  }

  if (fclose(f) != 0)
    return EIO;

  return 0;
}

int http_client_send_multi(struct HttpClient *client,
                           struct HttpRequest *const *requests,
                           size_t num_requests, struct HttpFuture **futures,
                           http_multi_progress_cb progress_cb, void *user_data,
                           int fail_fast) {
  size_t i;
  int rc;
  struct HttpMultiRequest multi;

  if (!client || !requests || num_requests == 0 || !futures) {
    return EINVAL;
  }

  (void)progress_cb;
  (void)user_data;
  (void)fail_fast;

  if (http_multi_request_init(&multi) != 0)
    return ENOMEM;

  for (i = 0; i < num_requests; ++i) {
    if (http_multi_request_add(&multi, requests[i]) != 0) {
      http_multi_request_free(&multi);
      return ENOMEM;
    }
  }

  /* Dispatch based on modality */
  switch (client->config.modality) {
  case MODALITY_ASYNC:
    if (client->send_multi && client->loop) {
      rc = client->send_multi(client->transport, client->loop, &multi, futures);
    } else {
      rc = ENOTSUP;
    }
    break;

  case MODALITY_SYNC:
  default:
    /* Fallback to simple sequential execution if backend doesn't support multi
     * natively or is sync */
    rc = 0;
    for (i = 0; i < num_requests; ++i) {
      struct HttpResponse *res = NULL;
      int req_rc;

      req_rc = client->send(client->transport, requests[i], &res);
      futures[i]->response = res;
      futures[i]->error_code = req_rc;
      futures[i]->is_ready = 1;

      if (fail_fast && req_rc != 0) {
        rc = req_rc;
        break; /* Stop processing further requests */
      }
    }
    break;
  }

  http_multi_request_free(&multi);
  return rc;
}
