/**
 * @file http_curl.c
 * @brief Implementation of the Libcurl backend.
 *
 * Handles HTTP requests via libcurl.
 * Includes support for Multipart/Form-Data by ensuring parts are flattened
 * before transmission if internal curl_mime isn't used (to maintain ABI
 * consistency with other transports).
 *
 * @author Samuel Marks
 */

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Defines for C89 string functions if missing */
#if defined(_WIN32) || defined(__WIN32__) || defined(__WINDOWS__)
#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
#define strdup _strdup
#endif
#else
#endif

#include <curl/curl.h>

#include <c_abstract_http/http_curl.h>
#include <c_abstract_http/str.h>

/**
 * @brief Opaque context definition.
 */
struct HttpTransportContext {
  CURL *curl;                       /**< The libcurl handle */
  struct HttpCookieJar *cookie_jar; /**< Weak reference to shared cookie jar */
};

/**
 * @brief Context for the Curl write callback.
 */
struct CurlWriteContext {
  struct MemoryStruct {
    char *memory;
    size_t size;
  } chunk;
  const struct HttpRequest *req;
  int user_aborted;
};

/**
 * @brief Libcurl write callback.
 * Appends data to buffer and maintains null-terminator safety,
 * or delegates to a user-provided on_chunk callback.
 */
static size_t math_write_memory_callback(void *contents, size_t size,
                                         size_t nmemb, void *userp) {
  size_t realsize = size * nmemb;
  struct CurlWriteContext *ctx = (struct CurlWriteContext *)userp;
  char *ptr;

  if (ctx->req && ctx->req->on_chunk) {
    int rc =
        ctx->req->on_chunk(ctx->req->on_chunk_user_data, contents, realsize);
    if (rc != 0) {
      ctx->user_aborted = rc;
      return 0; /* Returning less than realsize aborts the curl transfer */
    }
    return realsize;
  }

  /* Realloc to size + new_bytes + 1 (for null terminator) */
  ptr = (char *)realloc(ctx->chunk.memory, ctx->chunk.size + realsize + 1);
  if (!ptr) {
    /* Out of memory */
    return 0;
  }

  ctx->chunk.memory = ptr;
  memcpy(&(ctx->chunk.memory[ctx->chunk.size]), contents, realsize);
  ctx->chunk.size += realsize;
  ctx->chunk.memory[ctx->chunk.size] = 0; /* Null terminate for text safety */

  return realsize;
}

/**
 * @brief Libcurl read callback for streaming uploads.
 */
static /**
        * @brief Autogenerated docstring
        */
    size_t
    math_curl_read_callback(char *buffer, size_t size, size_t nitems,
                            void *userdata) {
  const struct HttpRequest *req = (const struct HttpRequest *)userdata;
  size_t max_bytes = size * nitems;
  size_t out_read = 0;
  int rc;

  if (!req || !req->read_chunk) {
    return CURL_READFUNC_ABORT;
  }

  rc = req->read_chunk(req->read_chunk_user_data, buffer, max_bytes, &out_read);
  if (rc != 0) {
    return CURL_READFUNC_ABORT;
  }

  return out_read;
}

static /**
        * @brief Autogenerated docstring
        */
    int
    format_header(const char *key, const char *value, char **_out_val) {
  size_t len = strlen(key) + 2 + strlen(value) + 1;
  char *buf = (char *)malloc(len);
  if (buf) {
#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
    sprintf_s(buf, len, "%s: %s", key, value);
#else
    sprintf(buf, "%s: %s", key, value);
#endif
  }
  {
    *_out_val = buf;
    return 0;
  }
}

static /**
        * @brief Autogenerated docstring
        */
    int
    map_curl_error(CURLcode res) {
  switch (res) {
  case CURLE_OK:
    return 0;
  case CURLE_UNSUPPORTED_PROTOCOL:
    return EINVAL;
  case CURLE_COULDNT_RESOLVE_PROXY:
  case CURLE_COULDNT_RESOLVE_HOST:
    return EHOSTUNREACH;
  case CURLE_COULDNT_CONNECT:
    return ECONNREFUSED;
  case CURLE_OPERATION_TIMEDOUT:
    return ETIMEDOUT;
  case CURLE_SSL_CONNECT_ERROR:
  case CURLE_PEER_FAILED_VERIFICATION:
    return EACCES;
  case CURLE_OUT_OF_MEMORY:
    return ENOMEM;
  case CURLE_TOO_MANY_REDIRECTS:
    return ELOOP;
  case CURLE_SEND_ERROR:
  case CURLE_RECV_ERROR:
    return EIO;
  default:
    return EIO;
  }
}

/**
 * @brief Autogenerated docstring
 */
static int g_curl_init_count = 0;
int http_curl_global_init(void) {
  if (g_curl_init_count == 0) {
    if (curl_global_init(CURL_GLOBAL_ALL) != 0) {
      return EIO;
    }
  }
  g_curl_init_count++;
  return 0;
}

/**
 * @brief Autogenerated docstring
 */
void http_curl_global_cleanup(void) {
  if (g_curl_init_count > 0) {
    g_curl_init_count--;
    if (g_curl_init_count == 0) {
      curl_global_cleanup();
    }
  }
}

/**
 * @brief Autogenerated docstring
 */
int http_curl_context_init(struct HttpTransportContext **const ctx) {
  if (!ctx)
    return EINVAL;

  *ctx = (struct HttpTransportContext *)malloc(
      sizeof(struct HttpTransportContext));
  if (!*ctx)
    return ENOMEM;

  (*ctx)->curl = curl_easy_init();
  if (!(*ctx)->curl) {
    free(*ctx);
    *ctx = NULL;
    return EIO;
  }

  return 0;
}

/**
 * @brief Autogenerated docstring
 */
void http_curl_context_free(struct HttpTransportContext *ctx) {
  if (ctx) {
    if (ctx->curl)
      curl_easy_cleanup(ctx->curl);
    free(ctx);
  }
}

/**
 * @brief Autogenerated docstring
 */
int http_curl_config_apply(struct HttpTransportContext *ctx,
                           const struct HttpConfig *config) {
  if (!ctx || !ctx->curl || !config)
    return EINVAL;

  if (curl_easy_setopt(ctx->curl, CURLOPT_TIMEOUT_MS, config->timeout_ms) !=
      CURLE_OK)
    return EIO;

  if (curl_easy_setopt(ctx->curl, CURLOPT_CONNECTTIMEOUT_MS,
                       config->timeout_ms) != CURLE_OK)
    return EIO;

  if (curl_easy_setopt(ctx->curl, CURLOPT_SSL_VERIFYPEER,
                       config->verify_peer ? 1L : 0L) != CURLE_OK)
    return EIO;
  if (curl_easy_setopt(ctx->curl, CURLOPT_SSL_VERIFYHOST,
                       config->verify_host ? 2L : 0L) != CURLE_OK)
    return EIO;

  if (curl_easy_setopt(ctx->curl, CURLOPT_FOLLOWLOCATION,
                       config->follow_redirects ? 1L : 0L) != CURLE_OK)
    return EIO;

  if (config->user_agent) {
    if (curl_easy_setopt(ctx->curl, CURLOPT_USERAGENT, config->user_agent) !=
        CURLE_OK)
      return EIO;
  }

  if (config->proxy_url) {
    if (curl_easy_setopt(ctx->curl, CURLOPT_PROXY, config->proxy_url) !=
        CURLE_OK)
      return EIO;

    if (config->proxy_username && config->proxy_password) {
      if (curl_easy_setopt(ctx->curl, CURLOPT_PROXYUSERNAME,
                           config->proxy_username) != CURLE_OK)
        return EIO;
      if (curl_easy_setopt(ctx->curl, CURLOPT_PROXYPASSWORD,
                           config->proxy_password) != CURLE_OK)
        return EIO;
    }
  } else {
    curl_easy_setopt(ctx->curl, CURLOPT_PROXY, "");
  }

  if (config->cookie_jar) {
    ctx->cookie_jar = config->cookie_jar;
    /* Enable curl's cookie engine without reading a file */
    if (curl_easy_setopt(ctx->curl, CURLOPT_COOKIEFILE, "") != CURLE_OK)
      return EIO;
    /* Instruct curl to write cookies to a dummy state (handled manually or via
     * curl's getinfo later) */
  } else {
    ctx->cookie_jar = NULL;
  }

  return 0;
}

/**
 * @brief Autogenerated docstring
 */
int http_curl_send(struct HttpTransportContext *ctx,
                   const struct HttpRequest *req,
                   struct HttpResponse **const res) {
  char *_ast_format_header_0;
  CURLcode res_code;
  struct curl_slist *headers = NULL;
  struct CurlWriteContext write_ctx;
  long response_code = 0;
  struct HttpResponse *new_res = NULL;
  int rc = 0;
  size_t i;
  void *payload = NULL;
  size_t payload_len = 0;

  if (!ctx || !ctx->curl || !req || !res)
    return EINVAL;

  payload = req->body;
  payload_len = req->body_len;

  /* Flatten parts if necessary */
  if (req->parts.count > 0 && !payload) {
    return EINVAL;
  }

  write_ctx.chunk.memory = (char *)malloc(1);
  write_ctx.chunk.size = 0;
  if (!write_ctx.chunk.memory)
    return ENOMEM;
  write_ctx.chunk.memory[0] = '\0';
  write_ctx.req = req;
  write_ctx.user_aborted = 0;

  curl_easy_setopt(ctx->curl, CURLOPT_URL, req->url);

  if (req->read_chunk) {
    switch (req->method) {
    case HTTP_PUT:
    case HTTP_POST:
    case HTTP_PATCH:
    case HTTP_QUERY:
      curl_easy_setopt(ctx->curl, CURLOPT_UPLOAD, 1L);
      if (req->method == HTTP_PUT) {
        curl_easy_setopt(ctx->curl, CURLOPT_CUSTOMREQUEST, "PUT");
      } else if (req->method == HTTP_POST) {
        curl_easy_setopt(ctx->curl, CURLOPT_CUSTOMREQUEST, "POST");
      } else if (req->method == HTTP_PATCH) {
        curl_easy_setopt(ctx->curl, CURLOPT_CUSTOMREQUEST, "PATCH");
      } else if (req->method == HTTP_QUERY) {
        curl_easy_setopt(ctx->curl, CURLOPT_CUSTOMREQUEST, "QUERY");
      }
      curl_easy_setopt(ctx->curl, CURLOPT_READFUNCTION,
                       math_curl_read_callback);
      curl_easy_setopt(ctx->curl, CURLOPT_READDATA, (void *)req);
      if (req->expected_body_len > 0) {
        curl_easy_setopt(ctx->curl, CURLOPT_INFILESIZE_LARGE,
                         (curl_off_t)req->expected_body_len);
      }
      break;
    default:
      /* other methods mostly ignore upload streams or we fallback */
      break;
    }
  } else {
    switch (req->method) {
    case HTTP_GET:
      curl_easy_setopt(ctx->curl, CURLOPT_HTTPGET, 1L);
      break;
    case HTTP_POST:
      curl_easy_setopt(ctx->curl, CURLOPT_POST, 1L);
      if (payload && payload_len > 0) {
        curl_easy_setopt(ctx->curl, CURLOPT_POSTFIELDS, payload);
        curl_easy_setopt(ctx->curl, CURLOPT_POSTFIELDSIZE, (long)payload_len);
      }
      break;
    case HTTP_PUT:
      curl_easy_setopt(ctx->curl, CURLOPT_CUSTOMREQUEST, "PUT");
      if (payload && payload_len > 0) {
        curl_easy_setopt(ctx->curl, CURLOPT_POSTFIELDS, payload);
        curl_easy_setopt(ctx->curl, CURLOPT_POSTFIELDSIZE, (long)payload_len);
      }
      break;
    case HTTP_DELETE:
      curl_easy_setopt(ctx->curl, CURLOPT_CUSTOMREQUEST, "DELETE");
      break;
    case HTTP_HEAD:
      curl_easy_setopt(ctx->curl, CURLOPT_NOBODY, 1L);
      break;
    case HTTP_PATCH:
      curl_easy_setopt(ctx->curl, CURLOPT_CUSTOMREQUEST, "PATCH");
      if (payload && payload_len > 0) {
        curl_easy_setopt(ctx->curl, CURLOPT_POSTFIELDS, payload);
        curl_easy_setopt(ctx->curl, CURLOPT_POSTFIELDSIZE, (long)payload_len);
      }
      break;
    case HTTP_QUERY:
      curl_easy_setopt(ctx->curl, CURLOPT_CUSTOMREQUEST, "QUERY");
      if (payload && payload_len > 0) {
        curl_easy_setopt(ctx->curl, CURLOPT_POSTFIELDS, payload);
        curl_easy_setopt(ctx->curl, CURLOPT_POSTFIELDSIZE, (long)payload_len);
      }
      break;
    default:
      curl_easy_setopt(ctx->curl, CURLOPT_HTTPGET, 1L);
      break;
    }
  }

  for (i = 0; i < req->headers.count; ++i) {
    char *h_str =
        (format_header(req->headers.headers[i].key,
                       req->headers.headers[i].value, &_ast_format_header_0),
         _ast_format_header_0);
    if (!h_str) {
      rc = ENOMEM;
      goto cleanup;
    }
    headers = curl_slist_append(headers, h_str);
    free(h_str);
    if (!headers) {
      rc = ENOMEM;
      goto cleanup;
    }
  }
  if (headers) {
    curl_easy_setopt(ctx->curl, CURLOPT_HTTPHEADER, headers);
  }

  curl_easy_setopt(ctx->curl, CURLOPT_WRITEFUNCTION,
                   math_write_memory_callback);
  curl_easy_setopt(ctx->curl, CURLOPT_WRITEDATA, (void *)&write_ctx);

  res_code = curl_easy_perform(ctx->curl);

  if (res_code != CURLE_OK) {
    if (write_ctx.user_aborted != 0) {
      rc = write_ctx.user_aborted;
    } else {
      rc = map_curl_error(res_code);
    }
    goto cleanup;
  }

  curl_easy_getinfo(ctx->curl, CURLINFO_RESPONSE_CODE, &response_code);

  new_res = (struct HttpResponse *)calloc(1, sizeof(struct HttpResponse));
  if (!new_res) {
    rc = ENOMEM;
    goto cleanup;
  }

  if (http_response_init(new_res) != 0) {
    free(new_res);
    rc = ENOMEM;
    goto cleanup;
  }

  /* Sync cookies back to jar if provided */
  if (ctx->cookie_jar) {
    struct curl_slist *cookies = NULL;
    if (curl_easy_getinfo(ctx->curl, CURLINFO_COOKIELIST, &cookies) ==
            CURLE_OK &&
        cookies) {
      struct curl_slist *each = cookies;
      while (each) {
        /* libcurl returns cookies in netscape format:
           domain flag path secure expiration name value */
        char domain[256], flag[16], path[256], secure[16], name[256],
            value[2048];
        long expiration;
        /* Very basic parsing of the tab-separated format for the name/value */
        if (sscanf(each->data, "%255s\t%15s\t%255s\t%15s\t%ld\t%255s\t%2047s",
                   domain, flag, path, secure, &expiration, name, value) == 7) {
          http_cookie_jar_set(ctx->cookie_jar, name, value);
        }
        each = each->next;
      }
      curl_slist_free_all(cookies);
    }
  }

  new_res->status_code = (int)response_code;
  if (req->on_chunk) {
    free(write_ctx.chunk.memory);
    write_ctx.chunk.memory = NULL;
    write_ctx.chunk.size = 0;
  }
  new_res->body = write_ctx.chunk.memory; /* Transfer ownership */
  new_res->body_len = write_ctx.chunk.size;
  write_ctx.chunk.memory = NULL; /* Prevent free in cleanup */

  *res = new_res;

cleanup:
  if (headers)
    curl_slist_free_all(headers);
  if (write_ctx.chunk.memory)
    free(write_ctx.chunk.memory);

  return rc;
}
