/**
 * @file http_libuv.c
 * @brief Implementation of the libuv backend.
 *
 * @author Samuel Marks
 */

/* clang-format off */
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <c_abstract_http/http_libuv.h>
#include <c_abstract_http/http_types.h>
#include <c_abstract_http/str.h>

#ifdef C_ABSTRACT_HTTP_USE_LIBUV
#include <uv.h>
#endif



/**
 * @brief Opaque context definition.
 */
/* clang-format on */
struct HttpTransportContext {
  struct HttpConfig config;
};

static int libuv_global_init_count = 0;

/**
 * @brief Autogenerated docstring
 */
int http_libuv_global_init(void) {
  libuv_global_init_count++;
  return 0;
}

/**
 * @brief Autogenerated docstring
 */
void http_libuv_global_cleanup(void) {
  if (libuv_global_init_count > 0) {
    libuv_global_init_count--;
  }
}

/**
 * @brief Autogenerated docstring
 */
int http_libuv_context_init(struct HttpTransportContext **ctx) {
  if (!ctx) {
    return EINVAL;
  }
  *ctx = (struct HttpTransportContext *)malloc(
      sizeof(struct HttpTransportContext));
  if (!*ctx) {
    return ENOMEM;
  }
  memset(*ctx, 0, sizeof(struct HttpTransportContext));
  return 0;
}

/**
 * @brief Autogenerated docstring
 */
void http_libuv_context_free(struct HttpTransportContext *ctx) {
  if (ctx) {
    free(ctx);
  }
}

/**
 * @brief Autogenerated docstring
 */
int http_libuv_config_apply(struct HttpTransportContext *ctx,
                            const struct HttpConfig *config) {
  if (!ctx || !config) {
    return EINVAL;
  }
  ctx->config = *config;
  return 0;
}

static int get_method_str(enum HttpMethod method, const char **out_str) {
  switch (method) {
  case HTTP_GET:
    *out_str = "GET";
    break;
  case HTTP_POST:
    *out_str = "POST";
    break;
  case HTTP_PUT:
    *out_str = "PUT";
    break;
  case HTTP_DELETE:
    *out_str = "DELETE";
    break;
  case HTTP_PATCH:
    *out_str = "PATCH";
    break;
  case HTTP_HEAD:
    *out_str = "HEAD";
    break;
  case HTTP_OPTIONS:
    *out_str = "OPTIONS";
    break;
  case HTTP_TRACE:
    *out_str = "TRACE";
    break;
  case HTTP_QUERY:
    *out_str = "QUERY";
    break;
  case HTTP_CONNECT:
    *out_str = "CONNECT";
    break;
  default:
    *out_str = "GET";
    break;
  }
  return 0;
}

#ifdef C_ABSTRACT_HTTP_USE_LIBUV

struct libuv_state {
  uv_loop_t loop;
  uv_tcp_t socket;
  uv_connect_t connect_req;
  uv_getaddrinfo_t resolver;
  uv_timer_t timer;
  uv_write_t write_req;

  struct HttpTransportContext *ctx;
  const struct HttpRequest *req;
  struct HttpResponse **res;

  char *req_buf;
  size_t req_len;
  size_t req_pos; /* for chunked writing */

  char *res_buf;
  size_t res_len;
  size_t res_cap;

  int headers_parsed;
  int error_code;
  int done;
  int has_socket;
  int has_timer;
};

static void libuv_on_close(uv_handle_t *handle) { (void)handle; }

static void libuv_finish(struct libuv_state *state, int error) {
  if (state->done)
    return;
  state->done = 1;
  state->error_code = error;

  if (state->has_timer) {
    uv_timer_stop(&state->timer);
    uv_close((uv_handle_t *)&state->timer, libuv_on_close);
    state->has_timer = 0;
  }

  if (state->has_socket && !uv_is_closing((uv_handle_t *)&state->socket)) {
    uv_close((uv_handle_t *)&state->socket, libuv_on_close);
    state->has_socket = 0;
  }
}

static void libuv_on_timeout(uv_timer_t *handle) {
  struct libuv_state *state = (struct libuv_state *)handle->data;
  libuv_finish(state, ETIMEDOUT);
}

static void libuv_alloc_cb(uv_handle_t *handle, size_t suggested_size,
                           uv_buf_t *buf) {
  struct libuv_state *state = (struct libuv_state *)handle->data;
  size_t avail = state->res_cap - state->res_len;
  (void)suggested_size;

  if (avail < 4096) {
    size_t new_cap = state->res_cap == 0 ? 8192 : state->res_cap * 2;
    char *new_buf = (char *)realloc(state->res_buf, new_cap);
    if (!new_buf) {
      buf->base = NULL;
      buf->len = 0;
      return;
    }
    state->res_buf = new_buf;
    state->res_cap = new_cap;
    avail = state->res_cap - state->res_len;
  }

  buf->base = state->res_buf + state->res_len;
  buf->len = (ULONG)avail; /* explicit cast to ULONG for libuv wincompat */
}

static void parse_headers(struct libuv_state *state) {
  struct HttpResponse *r;
  char *p;
  char *end;

  if (state->headers_parsed)
    return;

  p = strstr(state->res_buf, "\r\n\r\n");
  if (!p)
    return;

  state->headers_parsed = 1;
  *state->res = (struct HttpResponse *)malloc(sizeof(struct HttpResponse));
  if (!*state->res) {
    libuv_finish(state, ENOMEM);
    return;
  }
  r = *state->res;
  memset(r, 0, sizeof(struct HttpResponse));

  /* Parse status line */
  {
    char *space = strchr(state->res_buf, ' ');
    if (space) {
      r->status_code = atoi(space + 1);
    }
  }

  http_headers_init(&r->headers);

  /* Parse headers */
  p = strchr(state->res_buf, '\n');
  if (p)
    p++;

  end = strstr(state->res_buf, "\r\n\r\n");
  while (p && p < end && *p != '\r') {
    char *line_end = strchr(p, '\r');
    if (line_end && line_end < end) {
      *line_end = '\0';
      {
        char *colon = strchr(p, ':');
        if (colon) {
          char *val = colon + 1;
          *colon = '\0';
          while (*val == ' ')
            val++;
          http_headers_add(&r->headers, p, val);
        }
      }
      p = line_end + 2; /* skip \r\n */
    } else {
      break;
    }
  }

  {
    size_t hdr_len = (end - state->res_buf) + 4;
    size_t body_len = state->res_len - hdr_len;

    if (state->req->on_chunk) {
      if (body_len > 0) {
        int chunk_rc = state->req->on_chunk(state->req->on_chunk_user_data,
                                            state->res_buf + hdr_len, body_len);
        if (chunk_rc != 0) {
          libuv_finish(state, ECANCELED);
          return;
        }
      }
      state->res_len = hdr_len; /* consumed */
    } else {
      r->body_len = body_len;
      if (body_len > 0) {
        r->body = malloc(body_len);
        if (!r->body) {
          libuv_finish(state, ENOMEM);
          return;
        }
        memcpy(r->body, state->res_buf + hdr_len, body_len);
      }
    }
  }
}

static void libuv_on_read(uv_stream_t *stream, ssize_t nread,
                          const uv_buf_t *buf) {
  struct libuv_state *state = (struct libuv_state *)stream->data;
  (void)buf;

  if (nread < 0) {
    if (nread != UV_EOF) {
      /* Connection error */
      libuv_finish(state, ECONNREFUSED);
    } else {
      if (!state->headers_parsed) {
        parse_headers(state);
      }
      libuv_finish(state, 0);
    }
    return;
  }

  state->res_len += nread;

  if (!state->headers_parsed) {
    parse_headers(state);
  } else if (state->req->on_chunk) {
    /* Send newly read chunk */
    int chunk_rc =
        state->req->on_chunk(state->req->on_chunk_user_data,
                             state->res_buf + state->res_len - nread, nread);
    if (chunk_rc != 0) {
      libuv_finish(state, ECANCELED);
      return;
    }
    state->res_len -= nread; /* Reset buffer logically */
  } else {
    /* Accumulate into r->body */
    struct HttpResponse *r = *state->res;
    if (r) {
      char *new_body = (char *)realloc(r->body, r->body_len + nread);
      if (!new_body) {
        libuv_finish(state, ENOMEM);
        return;
      }
      memcpy(new_body + r->body_len, state->res_buf + state->res_len - nread,
             nread);
      r->body = new_body;
      r->body_len += nread;
    }
  }
}

static void libuv_on_write(uv_write_t *req, int status) {
  struct libuv_state *state = (struct libuv_state *)req->data;
  if (status < 0) {
    libuv_finish(state, EIO);
    return;
  }

  /* After writing request, start reading response */
  uv_read_start((uv_stream_t *)&state->socket, libuv_alloc_cb, libuv_on_read);
}

static void libuv_on_connect(uv_connect_t *req, int status) {
  struct libuv_state *state = (struct libuv_state *)req->data;
  uv_buf_t buf;

  if (status < 0) {
    libuv_finish(state, ECONNREFUSED);
    return;
  }

  state->write_req.data = state;
  buf = uv_buf_init(state->req_buf, (unsigned int)state->req_len);

  if (uv_write(&state->write_req, (uv_stream_t *)&state->socket, &buf, 1,
               libuv_on_write) < 0) {
    libuv_finish(state, EIO);
  }
}

static void libuv_on_resolved(uv_getaddrinfo_t *resolver, int status,
                              struct addrinfo *res) {
  struct libuv_state *state = (struct libuv_state *)resolver->data;

  if (status < 0) {
    libuv_finish(state, EHOSTUNREACH);
    uv_freeaddrinfo(res);
    return;
  }

  state->connect_req.data = state;

  if (uv_tcp_connect(&state->connect_req, &state->socket, res->ai_addr,
                     libuv_on_connect) < 0) {
    libuv_finish(state, ECONNREFUSED);
  }

  uv_freeaddrinfo(res);
}

static int parse_url(const char *url, char **host, int *port, char **path) {
  const char *p;
  const char *host_start;
  const char *port_start;
  const char *path_start;
  size_t host_len;
  char *_ast_strdup = NULL;

  if (!url)
    return EINVAL;

  if (strncmp(url, "http://", 7) == 0) {
    p = url + 7;
    *port = 80;
  } else if (strncmp(url, "https://", 8) == 0) {
    p = url + 8;
    *port = 443;
  } else {
    p = url;
    *port = 80;
  }

  host_start = p;
  path_start = strchr(p, '/');
  port_start = strchr(p, ':');

  if (path_start && port_start && port_start > path_start) {
    port_start = NULL;
  }

  if (port_start) {
    host_len = port_start - host_start;
    *port = atoi(port_start + 1);
  } else if (path_start) {
    host_len = path_start - host_start;
  } else {
    host_len = strlen(host_start);
  }

  *host = (char *)malloc(host_len + 1);
  if (!*host)
    return ENOMEM;
  strncpy(*host, host_start, host_len);
  (*host)[host_len] = '\0';

  if (path_start) {
    c_cdd_strdup(path_start, &_ast_strdup);
    *path = _ast_strdup;
  } else {
    c_cdd_strdup("/", &_ast_strdup);
    *path = _ast_strdup;
  }

  return 0;
}

#endif /* C_ABSTRACT_HTTP_USE_LIBUV */

/**
 * @brief Autogenerated docstring
 */
int http_libuv_send(struct HttpTransportContext *ctx,
                    const struct HttpRequest *req, struct HttpResponse **res) {
#ifdef C_ABSTRACT_HTTP_USE_LIBUV
  struct libuv_state state;
  char *host = NULL;
  int port = 0;
  char *path = NULL;
  char port_str[16];
  const char *method_str;
  size_t i;
  size_t req_cap = 4096;
  struct addrinfo hints;

  if (!ctx || !req || !res)
    return EINVAL;

  /* Check if parts are flattened properly before attempting to send them */
  if (req->parts.count > 0 && !req->body) {
    return EINVAL;
  }

  memset(&state, 0, sizeof(state));
  state.ctx = ctx;
  state.req = req;
  state.res = res;
  *res = NULL;

  if (parse_url(req->url, &host, &port, &path) != 0) {
    if (host)
      free(host);
    if (path)
      free(path);
    return EINVAL;
  }

#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
  sprintf_s(port_str, sizeof(port_str), "%d", port);
#else
  sprintf(port_str, "%d", port);
#endif

  get_method_str(req->method, &method_str);

  /* Build request buffer */
  state.req_buf = (char *)malloc(req_cap);
  if (!state.req_buf) {
    free(host);
    free(path);
    return ENOMEM;
  }

#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
  state.req_len =
      sprintf_s(state.req_buf, req_cap,
                "%s %s HTTP/1.1\r\nHost: %s:%d\r\nConnection: close\r\n",
                method_str, path, host, port);
#else
  state.req_len =
      sprintf(state.req_buf,
               "%s %s HTTP/1.1\r\nHost: %s:%d\r\nConnection: close\r\n",
               method_str, path, host, port);
#endif

  free(host);
  free(path);

  for (i = 0; i < req->headers.count; i++) {
    size_t hdr_len = strlen(req->headers.headers[i].key) +
                     strlen(req->headers.headers[i].value) + 4;
    if (state.req_len + hdr_len > req_cap) {
      req_cap *= 2;
      state.req_buf = (char *)realloc(state.req_buf, req_cap);
    }
#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
    state.req_len += sprintf_s(
        state.req_buf + state.req_len, req_cap - state.req_len, "%s: %s\r\n",
        req->headers.headers[i].key, req->headers.headers[i].value);
#else
    state.req_len += sprintf(
        state.req_buf + state.req_len, "%s: %s\r\n",
        req->headers.headers[i].key, req->headers.headers[i].value);
#endif
  }

  /* Body length */
  if (req->read_chunk && req->expected_body_len > 0) {
#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
    state.req_len += sprintf_s(
        state.req_buf + state.req_len, req_cap - state.req_len,
        "Content-Length: %" NUM_FORMAT "\r\n", req->expected_body_len);
#else
    state.req_len +=
        sprintf(state.req_buf + state.req_len,
                 "Content-Length: " NUM_FORMAT "\r\n", req->expected_body_len);
#endif
  } else if (req->body_len > 0) {
#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
    state.req_len +=
        sprintf_s(state.req_buf + state.req_len, req_cap - state.req_len,
                  "Content-Length: %" NUM_FORMAT "\r\n", req->body_len);
#else
    state.req_len +=
        sprintf(state.req_buf + state.req_len,
                 "Content-Length: " NUM_FORMAT "\r\n", req->body_len);
#endif
  }

#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
  state.req_len +=
      sprintf_s(state.req_buf + state.req_len, req_cap - state.req_len, "\r\n");
#else
  state.req_len +=
      sprintf(state.req_buf + state.req_len, "\r\n");
#endif

  /* Append body if not chunked */
  if (req->body && req->body_len > 0) {
    if (state.req_len + req->body_len > req_cap) {
      req_cap = state.req_len + req->body_len + 1;
      state.req_buf = (char *)realloc(state.req_buf, req_cap);
    }
    memcpy(state.req_buf + state.req_len, req->body, req->body_len);
    state.req_len += req->body_len;
  } else if (req->read_chunk) {
    /* Read all from chunk into buffer for simplicity of mock */
    size_t out_read;
    char chunk_buf[4096];
    while (req->read_chunk(req->read_chunk_user_data, chunk_buf,
                           sizeof(chunk_buf), &out_read) == 0) {
      if (out_read == 0)
        break;
      if (state.req_len + out_read > req_cap) {
        req_cap = (state.req_len + out_read) * 2;
        state.req_buf = (char *)realloc(state.req_buf, req_cap);
      }
      memcpy(state.req_buf + state.req_len, chunk_buf, out_read);
      state.req_len += out_read;
    }
  }

  /* Init libuv */
  uv_loop_init(&state.loop);
  uv_tcp_init(&state.loop, &state.socket);
  state.has_socket = 1;
  state.socket.data = &state;

  if (ctx->config.timeout_ms > 0) {
    uv_timer_init(&state.loop, &state.timer);
    state.has_timer = 1;
    state.timer.data = &state;
    uv_timer_start(&state.timer, libuv_on_timeout, ctx->config.timeout_ms, 0);
  }

  memset(&hints, 0, sizeof(hints));
  hints.ai_family = AF_INET; /* Force IPv4 for mock server */
  hints.ai_socktype = SOCK_STREAM;
  hints.ai_protocol = IPPROTO_TCP;

  state.resolver.data = &state;
  if (uv_getaddrinfo(&state.loop, &state.resolver, libuv_on_resolved, host,
                     port_str, &hints) < 0) {
    libuv_finish(&state, EHOSTUNREACH);
  }

  /* Run event loop until done */
  uv_run(&state.loop, UV_RUN_DEFAULT);

  uv_loop_close(&state.loop);

  if (state.req_buf)
    free(state.req_buf);
  if (state.res_buf)
    free(state.res_buf);

  if (state.error_code != 0 && *res) {
    http_response_free(*res);
    free(*res);
    *res = NULL;
  }

  return state.error_code;
#else
  (void)ctx;
  (void)req;
  (void)res;
  return ENOTSUP;
#endif
}
