/**
 * @file http_wasm.c
 * @brief Implementation of the Wasm (Emscripten builtin-fetch) backend.
 *
 * @author Samuel Marks
 */

/* clang-format off */
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <c_abstract_http/http_types.h>
#include <c_abstract_http/http_wasm.h>
#include <c_abstract_http/str.h>

#ifdef __EMSCRIPTEN__
#include <emscripten/fetch.h>
#endif

/**
 * @brief Opaque context definition.
 */
/* clang-format on */
struct HttpTransportContext {
  struct HttpConfig config;
};

static int wasm_global_init_count = 0;

/**
 * @brief Autogenerated docstring
 */
int http_wasm_global_init(void) {
  wasm_global_init_count++;
  return 0;
}

/**
 * @brief Autogenerated docstring
 */
void http_wasm_global_cleanup(void) {
  if (wasm_global_init_count > 0) {
    wasm_global_init_count--;
  }
}

/**
 * @brief Autogenerated docstring
 */
int http_wasm_context_init(struct HttpTransportContext **ctx) {
  if (!ctx) {
    return EINVAL;
  }
  *ctx = (struct HttpTransportContext *)malloc(
      sizeof(struct HttpTransportContext));
  if (!*ctx) {
    return ENOMEM;
  }
  memset(*ctx, 0, sizeof(struct HttpTransportContext));
  return 0;
}

/**
 * @brief Autogenerated docstring
 */
void http_wasm_context_free(struct HttpTransportContext *ctx) {
  if (ctx) {
    free(ctx);
  }
}

/**
 * @brief Autogenerated docstring
 */
int http_wasm_config_apply(struct HttpTransportContext *ctx,
                           const struct HttpConfig *config) {
  if (!ctx || !config) {
    return EINVAL;
  }
  ctx->config = *config;
  return 0;
}

static int get_method_str(enum HttpMethod method, const char **out_str) {
  switch (method) {
  case HTTP_GET:
    *out_str = "GET";
    break;
  case HTTP_POST:
    *out_str = "POST";
    break;
  case HTTP_PUT:
    *out_str = "PUT";
    break;
  case HTTP_DELETE:
    *out_str = "DELETE";
    break;
  case HTTP_PATCH:
    *out_str = "PATCH";
    break;
  case HTTP_HEAD:
    *out_str = "HEAD";
    break;
  case HTTP_OPTIONS:
    *out_str = "OPTIONS";
    break;
  case HTTP_TRACE:
    *out_str = "TRACE";
    break;
  case HTTP_QUERY:
    *out_str = "QUERY";
    break;
  case HTTP_CONNECT:
    *out_str = "CONNECT";
    break;
  default:
    *out_str = "GET";
    break;
  }
  return 0;
}

/**
 * @brief Autogenerated docstring
 */
int http_wasm_send(struct HttpTransportContext *ctx,
                   const struct HttpRequest *req, struct HttpResponse **res) {
#ifdef __EMSCRIPTEN__
  emscripten_fetch_attr_t attr;
  emscripten_fetch_t *fetch;
  const char **headers = NULL;
  size_t headers_count = 0;
  size_t i;
  int rc = 0;
  char *body_buffer = NULL;
  size_t body_len = 0;

  if (!ctx || !req || !res) {
    return EINVAL;
  }

  *res = NULL;

  /* Check if parts are flattened properly before attempting to send them */
  if (req->parts.count > 0 && !req->body) {
    return EINVAL;
  }

  emscripten_fetch_attr_init(&attr);
  const char *method_str;
  get_method_str(req->method, &method_str);
  strcpy(attr.requestMethod, method_str);
  attr.attributes = EMSCRIPTEN_FETCH_SYNCHRONOUS;

  if (ctx->config.timeout_ms > 0) {
    attr.timeoutMSecs = (uint32_t)ctx->config.timeout_ms;
  }

  if (req->headers.count > 0) {
    headers = (const char **)malloc((req->headers.count * 2 + 1) *
                                    sizeof(const char *));
    if (!headers) {
      return ENOMEM;
    }
    for (i = 0; i < req->headers.count; i++) {
      headers[headers_count++] = req->headers.headers[i].key;
      headers[headers_count++] = req->headers.headers[i].value;
    }
    headers[headers_count] = NULL;
    attr.requestHeaders = headers;
  }

  if (req->read_chunk) {
    size_t cap = req->expected_body_len > 0 ? req->expected_body_len : 4096;
    size_t out_read;

    body_buffer = (char *)malloc(cap);
    if (!body_buffer) {
      rc = ENOMEM;
      goto cleanup;
    }

    while (1) {
      int chunk_rc;
      if (body_len == cap) {
        char *new_buf;
        cap *= 2;
        new_buf = (char *)realloc(body_buffer, cap);
        if (!new_buf) {
          rc = ENOMEM;
          goto cleanup;
        }
        body_buffer = new_buf;
      }

      chunk_rc =
          req->read_chunk(req->read_chunk_user_data, body_buffer + body_len,
                          cap - body_len, &out_read);
      if (chunk_rc != 0) {
        rc = ECANCELED;
        goto cleanup;
      }
      if (out_read == 0) {
        break;
      }
      body_len += out_read;
    }

    attr.requestData = body_buffer;
    attr.requestDataSize = body_len;
  } else if (req->body) {
    attr.requestData = (const char *)req->body;
    attr.requestDataSize = req->body_len;
  }

  fetch = emscripten_fetch(&attr, req->url);

  if (!fetch) {
    rc = EIO;
    goto cleanup;
  }

  if (fetch->status == 0 && fetch->numBytes == 0 && fetch->readyState != 4) {
    emscripten_fetch_close(fetch);
    rc = ETIMEDOUT;
    goto cleanup;
  }

  *res = (struct HttpResponse *)malloc(sizeof(struct HttpResponse));
  if (!*res) {
    emscripten_fetch_close(fetch);
    rc = ENOMEM;
    goto cleanup;
  }
  memset(*res, 0, sizeof(struct HttpResponse));

  (*res)->status_code = fetch->status;

  if (fetch->numBytes > 0) {
    (*res)->body = malloc(fetch->numBytes);
    if (!(*res)->body) {
      emscripten_fetch_close(fetch);
      free(*res);
      *res = NULL;
      rc = ENOMEM;
      goto cleanup;
    }
    memcpy((*res)->body, fetch->data, fetch->numBytes);
    (*res)->body_len = fetch->numBytes;

    if (req->on_chunk) {
      int chunk_rc = req->on_chunk(req->on_chunk_user_data, (*res)->body,
                                   (*res)->body_len);
      if (chunk_rc != 0) {
        free((*res)->body);
        free(*res);
        *res = NULL;
        emscripten_fetch_close(fetch);
        rc = ECANCELED;
        goto cleanup;
      }
      /* If chunk callback consumed data, we free the response body */
      free((*res)->body);
      (*res)->body = NULL;
      (*res)->body_len = 0;
    }
  }

  {
    size_t hdrs_len = emscripten_fetch_get_response_headers_length(fetch);
    if (hdrs_len > 0) {
      char *hdrs_buf = (char *)malloc(hdrs_len + 1);
      if (hdrs_buf) {
        emscripten_fetch_get_response_headers(fetch, hdrs_buf, hdrs_len + 1);
        http_headers_init(&(*res)->headers);
        {
          char *p = hdrs_buf;
          char *end = hdrs_buf + hdrs_len;
          while (p < end && *p) {
            char *line_end = strchr(p, '\r');
            if (!line_end) {
              line_end = strchr(p, '\n');
            }
            if (line_end) {
              *line_end = '\0';
            }
            if (*p) {
              char *colon = strchr(p, ':');
              if (colon) {
                char *val = colon + 1;
                *colon = '\0';
                while (*val == ' ') {
                  val++;
                }
                http_headers_add(&(*res)->headers, p, val);
              }
            }
            if (line_end) {
              p = line_end + 1;
              if (*p == '\n')
                p++;
            } else {
              break;
            }
          }
        }
        free(hdrs_buf);
      }
    }
  }

  emscripten_fetch_close(fetch);

cleanup:
  if (headers) {
    free(headers);
  }
  if (body_buffer) {
    free(body_buffer);
  }

  return rc;
#else
  (void)ctx;
  (void)req;
  (void)res;
  return ENOTSUP;
#endif
}
